### ISSUE TITLE
option to use off-line dictionary (e.g. aard2) to lookup/define words

### ISSUE THREAD

**Issue by frief** [lexica/lexica#11]
- allows usage when data connection is not available (or roaming)
- does not leak my language skills to Google
- could allow me (non native English speaker) to select freedict-eng-xyz-0.1.4.slob within aard2 to improve my language skills (clicking one of the "MISSED WORDS" would quickly take me there). To be honest: it would be perfect if I could select two languages there...

Don't get me wrong, I already like lexica as it is!)

**Comment by pserwylo** [comment]
Hi @frief, this sounds like a great improvement. I'm not a huge fan of Google as it is so this would be nice. I'm going to mark it as "help-wanted" in case anybody is able to submit patches. Otherwise I'll look at it in the future when I get some time. Thanks.

**Comment by pserwylo** [comment]
One thing that occurs to me right now is that AARD2 is not on F-Droid due to some inclusion-criteria problems which require addressing before it is built for F-Droid. As such, I don't have access to AARD2 to write this feature.

I had a quick look at fbreader which seems to have an `OpenDictionary` tool they wrote. Looks like it would be awesome as a seaprate library, but right now is bundled with fbreader. Perhaps I'll see in the future if they would be willing to allow that to be extracted into a separate library they can maintain, and we (and other projects) can use (rather than re-inventing the wheel).

**Comment by triNem** [comment]
Quickdick could be an alternative. It is available on [F-droid](https://f-droid.org/en/packages/de.reimardoeffinger.quickdic/). It is rather lightweight (works on android 2.3).It features online and offline definitions and a lot of languages.

**Comment by frief** [comment]
Great -thanks JulianPaoloThiry and pserwylo! Would it be possible to integrate http://www.kiwix.org/ too?
(Kiwix has a similar feature set as AARD2 _and_ is available on F-Droid)
