### ISSUE TITLE
Add Brazilian Portuguese (pt_BR) dictionary

### ISSUE THREAD

**Issue by rffontenelle** [lexica/lexica#127]
Running `./add-lang.sh pt_BR` (passing 1 argument, note the underscore) works just fine. But when following the instructions in `assets/dictionary/README.md` to run `./add-lang.sh pt BR` (passing 2 arguments), it fails to read the correct file path and generates an empty dictionary. The following output is displayed:
```
lexica$ LC_ALL=C ./add-lang.sh pt BR
Error: The language "pt" is not known. This is probably because: the file "/usr/lib/aspell-0.60/pt.dat" can not be opened for reading.
Wrote assets/dictionaries/dictionary.pt_BR.txt
```
The directory's contents are:
```bash
$ ls -1 /usr/lib/aspell-0.60/pt*
/usr/lib/aspell-0.60/pt_BR_affix.dat
/usr/lib/aspell-0.60/pt_BR.dat
/usr/lib/aspell-0.60/pt_BR.multi
/usr/lib/aspell-0.60/pt_BR.rws
/usr/lib/aspell-0.60/pt_PT_affix.dat
/usr/lib/aspell-0.60/pt_PT.dat
/usr/lib/aspell-0.60/pt_PT.multi
/usr/lib/aspell-0.60/pt_PT-preao_affix.dat
/usr/lib/aspell-0.60/pt_PT-preao.dat
/usr/lib/aspell-0.60/pt_PT-preao.multi
/usr/lib/aspell-0.60/pt_PT-preao_repl.dat
/usr/lib/aspell-0.60/pt_PT-preao.rws
/usr/lib/aspell-0.60/pt_PT_repl.dat
/usr/lib/aspell-0.60/pt_PT.rws
```

**Environment:**
distro: Arch Linux 64-bit
packages:
- aspell 0.60.8-1
- aspell-pt 20161001-1

**Comment by pserwylo** [comment]
Hmm, good point, thanks for the report.

Indeed on my Ubuntu (18.04) machine, after installing the `aspell-pt` package (amoung others I've installed in the past), I get the following:

```
ls /usr/lib/aspell/ | grep -P '^\w\w(_\w\w)?(\.\w*)'
ca.alias
ca.dat
de_AT.alias
de_AT.multi
de_CH.alias
de_CH.multi
de.dat
de_DE.alias
de_DE.multi
de.multi
en_AU.multi
en_CA.multi
en.dat
en_GB.multi
en.multi
en_US.multi
es.dat
es.multi
es.rws
fa.dat
fa.multi
fr_CH.multi
fr.dat
fr_FR.multi
fr.multi
it.dat
it.multi
it.rws
nl.dat
nl.multi
nl.rws
pl.dat
pl.multi
pl.rws
pt_BR.dat
pt_BR.multi
pt_BR.rws
pt_PT.dat
pt_PT.multi
pt_PT.rws
ru.dat
ru.multi
ru.rws
sv.dat
sv.multi
sv.rws
```

Without being an aspell expert, it seems like most of the languages I have installed which have a locale associated with them also include just a vanilla `lang.dat` file in addition to the `lang_locale.dat` file.

As such, I also get the same error:

```
Error: The language "pt" is not known. This is probably because: the file "/usr/lib/aspell/pt.dat" can not be opened for reading.
Wrote assets/dictionaries/dictionary.pt_BR.txt
```

The aim of this script is to help with the process of extracting a wordlist from aspell, which boils down to:

```
aspell -l ${LANGUAGE_WITH_REGION} dump master | aspell -l ${LANGUAGE} expand | tr ' ' '\n' | awk 'length($0) < 10 && length($0) > 2' | sort -u
```

When you run the `add-lang.sh` script with `pt` and `BR` as arguments, then `LANGUAGE_WITH_REGION` would be `pt_BR` and `LANGUAGE` would be `pt`. 

Instead, you can run the command `aspell -l pt_BR dump master | aspell -l pt_BR expand | tr ' ' '\n' | awk 'length($0) < 10 && length($0) > 2' | sort -u > assets/dictionaries/dictionary.pt_BR.txt` (replacing the ${LANGUAGE} with `pt_BR` instead of `pt` which seems to work.

You'll want to double check the words though and do whatever post-processing you see fit in order to make the words appropriate for a fun game (sorry I'm of no help here!). For example, there are lots of words starting with `EUA-` and then a capital letter: e.g. `EUA-Santa`. Would it be appropriate to pipe through `grep -v -P ...some regex matching upper case characters...`? Or are there some words with uppercase characters which still belong in this wordlist?

**Comment by rffontenelle** [comment]
> (replacing the ${LANGUAGE} with pt_BR instead of pt which seems to work.

Yes, it did the job. Maybe the exception should be documented or the script adapted to permit it.

> You'll want to double check the words though and do whatever post-processing you see fit in order to make the words appropriate for a fun game (sorry I'm of no help here!). For example, there are lots of words starting with EUA- and then a capital letter: e.g. EUA-Santa. Would it be appropriate to pipe through grep -v -P ...some regex matching upper case characters...? Or are there some words with uppercase characters which still belong in this wordlist?

I started looking at it and definitely it need some filter. Don't know about uppercase, but I will check -- thanks.

Does uppercase has difference for the game?

**Comment by rffontenelle** [comment]
Also, are words with hyphen accepted in the dictionary?

**Comment by pserwylo** [comment]
Oh wow, I really dropped the ball on this, apologies for not responding. If you're still keen, I'd love to get your help getting `pt_BR` in Lexica.

**Regarding upper case**

The internal representations of letter are stored in a single case, and displayed in a single case. For display reasons we upper case them in English, but we can have individual languages show letters how they think most appropriate. Given Portugese uses a Latin based alphabet, it should probably do the same thing and *display* letters in upper case.

I guess the main reason I bring up upper case is because it may be a heuristic for which words make sense in Lexica (or indeed other Scrable-like games). For instance, an English language dictionary may include "ATM" for Automatic Teller Machine", but really an acronym is not suitable for such a game. Therefore, we ended up filtering out acronyms and proper nouns.

As I am not a Portuguese speaker, I am unable to comment on whether `EUA-Santa` is a word that makes sense to have in such a game.

**Regarding hyphens**

Good question. I don't think it would work very well. The tools in place now would end up treating the `-` character the same it treats any other letter in the alphabet. Therefore, you'd end up with a board that has `-`'s in it, which is probably sub-optimal.

**Comment by rffontenelle** [comment]
This probably my local issue, but I'm trying to test my dictionary and I'm getting this issue. Any suggestion where should I aim at?

```
$ ./gradlew buildDictionary_pt_BR

> Configure project :app
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /opt/android-sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Checking the license for package Android SDK Build-Tools 25.0.2 in /opt/android-sdk/licenses
Warning: License for package Android SDK Build-Tools 25.0.2 not accepted.
Checking the license for package Android SDK Platform 23 in /opt/android-sdk/licenses
Warning: License for package Android SDK Platform 23 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > You have not accepted the license agreements of the following SDK components:
     [Android SDK Build-Tools 25.0.2, Android SDK Platform 23].
     Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
     Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
   > Could not get unknown property 'assembleDebug' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

**Comment by pserwylo** [comment]
The issue you are facing is that you need to accept the license agreement from Android prior to using their SDK:

```
You have not accepted the license agreements of the following SDK components:
     [Android SDK Build-Tools 25.0.2, Android SDK Platform 23].
     Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
     Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

If you use Android Studio, you can probably do this by going Tools -> SDK Manager and then ensuring the relevant dependencies are up to date.

Perhaps it can also be done via the CLI using `sdkmanager`: https://developer.android.com/studio/command-line/sdkmanager, but I'm less sure how this works.

In the past, I know it was the bane of existence for many CI builds that you had to do dodgey hacks (such as piping `y` into the SDK installer) to ensure that the agreement was accepted prior to building.

**Comment by rffontenelle** [comment]
Progress! I was so focused in the missing NDK that I didn't see this license thing. Now I'm using Android Studio and successfully updated stuff, agreed with sutff and `./gradlew buildDictionary_pt_BR` finished with good status.

Now, I did not understand how to add subclass "Language" to the `libraries/trie` library (step 4 in [assets/dictionaries/README.md](https://github.com/lexica/lexica/blob/master/assets/dictionaries/README.md)). What should I do here?

**Comment by pserwylo** [comment]
Great news. This is probably the first tome someone other than I has gone through the documentation there, so we can treat this as a little user test of my documentation, which we can update afterwards to clarify any misunderstandings :)

The folder in [libraries/trie/src/main/java/main/java/com/serwylo/lexica/lang](https://github.com/lexica/lexica/tree/master/libraries/trie/src/main/java/com/serwylo/lexica/lang) has both a [`Language.java`](https://github.com/lexica/lexica/blob/master/libraries/trie/src/main/java/com/serwylo/lexica/lang/Language.java) class (the superclass of all languages), and a bunch of classes for each other language. Try copying the file of another language (e.g. [`Spanish.java`](https://github.com/lexica/lexica/blob/master/libraries/trie/src/main/java/com/serwylo/lexica/lang/Spanish.java)) and rename it (e.g. to `PortugueseBR.java`). Hopefully by reading the contents of the file, it will help you with the next few steps in the process.

FYI, if you forget where the `Language` class is located, then from Android Studio you can press Ctrl + N to search for classes, start typing "Language" and it will direct you to where the class is without you having to navigate the filesystem.

**Comment by rffontenelle** [comment]
Ok, created `PortugueseBR.java` based on Spanish.java (very similar, by the way), changed class name accordingly, replaced lang code 'es' to 'pt_BR'. Also added an entry in `Language.java` file.

This to mention that, regarding this step:
> Tell Lexica about your Language class - Add an entry to Language#getAllLanguages()

there is no such "getAllLanguages" in that file or in any other file in the source code. I assume it refers to the fromOrNull method in `Language.java` file.

Now, regarding `./gradlew analyseLanguage_pt_BR`, it has been running for 40 minutes with output like:
```Iteration: 829 (7350) [Min: 12, mean: 111, max: 352, stddev: 71, score: 7350```

and going up. Will it end at some point or should I interrupt?

**Comment by rffontenelle** [comment]
oh, ok. I finished after 48 minutes on the 5th run. Would be nice to be documented though.

**Comment by rffontenelle** [comment]
@pserwylo The best-scored board has a `'` character probably caused by "d'água" (de água = of water) and "d'ouro" (de ouro = of gold) constructions. Should I remove occurrences having `'`, or keep it to show that character in the board?

**Comment by ildar** [comment]
Is it at all worth using articles in games like Lexica?

**Comment by rffontenelle** [comment]
> Is it at all worth using articles in games like Lexica?

Hmm don't think so. Removing it.

**Comment by rffontenelle** [comment]
Reading [Scrabble letter distributions#Portuguese](https://en.wikipedia.org/wiki/Scrabble_letter_distributions#Portuguese):
> "While Ç is a separate tile, other diacritical marks are ignored."

Does it mean something in terms of configuration of my Language subclass?

**Comment by pserwylo** [comment]
Ah, the `getAllLanguages` method was created [during the last release](https://github.com/lexica/lexica/blob/master/libraries/trie/src/main/java/com/serwylo/lexica/lang/Language.java#L12). I'm assuming your local repo was cloned prior to this. This means you will run into conflicts when you merge back into master.

Are you comfortable with git? The best course of action will be to:

 * commit your work locally. 
 * git remote add upstream https://github.com/lexica/lexica.git
 * git fetch upstream
 * git rebase upstream/master
 * This will likely cause conflicts, which you would need to resolve (I find Android Studios conflict resolution tools great)
 * git add . && git commit (though if you used Android Studio, it will have done this for you)
 * git rebase --continue

(Apologies if you're familiar already. If you're not particularly confident with git you may want to backup the folder first. Once you have committed locally you can always find that commit again via the reflog,  but some like to have the assurance of a backup prior to rebasing and solving conflicts).

(Also forgive any typos, these commands are untested and written from my phone while I wait for my beautiful 10 week old baby to sleep at 4:43am :) 

Regarding `analyseLanguages`, thanks for the feedback. Feel free to of update that readme with something about how long it took (and the specs of you're machine because it is very processor intensive). In the future I think I could augment that script to show progress and estimated completion time which may be helpful.

Cheers,
Pete. 

On 14 May 2020 1:41:04 am AEST, Rafael Fontenelle <notifications@github.com> wrote:
>Ok, created `PortugueseBR.java` based on Spanish.java (very similar, by the way), changed class name accordingly, replaced lang code 'es' to 'pt_BR'. Also added an entry in `Language.java` file.
>
>This to mention that, regarding this step:
>> Tell Lexica about your Language class - Add an entry to Language#getAllLanguages()
>
>there is no such "getAllLanguages" in that file or in any other file in the source code. I assume it refers to the fromOrNull method in `Language.java` file.
>
>Now, regarding `./gradlew analyseLanguage_pt_BR`, it has been running for 40 minutes with output like:
>```Iteration: 829 (7350) [Min: 12, mean: 111, max: 352, stddev: 71, score: 7350```
>
>and going up. Will it end at some point or should I interrupt?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/lexica/lexica/issues/127#issuecomment-628074864
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pserwylo** [comment]
There is a broader issue with diacritics in lexica, see #71 for details. If the letter distribution you have from running analyseLanguages includes diacritics and Scrabble doesn't, just use your better judgement to assign a point value to that letter.

We can revisit in the future when we fix lexica with regards to #71.

On 14 May 2020 4:33:56 am AEST, Rafael Fontenelle <notifications@github.com> wrote:
>Reading [Scrabble letter distributions#Portuguese](https://en.wikipedia.org/wiki/Scrabble_letter_distributions#Portuguese):
>
>> "While Ç is a separate tile, other diacritical marks are ignored."
>
>
>
>Does it mean something in terms of configuration of my Language subclass?
>
>
>
>-- >
>You are receiving this because you were mentioned.
>
>Reply to this email directly or view it on GitHub:
>
>https://github.com/lexica/lexica/issues/127#issuecomment-628170396
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rffontenelle** [comment]
Regarding git conflicts, ✓. I solved it easily after rebasing my commits. I'm pretty much comfortable, but thanks for worrying.

Regarding normalization of diacritics Latin characters, that's the same case in Portuguese.  Should I do something on my side (e.g. removing accent of letters from the dictionary) or I just let it be solved by after that issue?

And sorry for taking your time while you're taking care of this blessing. Congrats!

**Comment by pserwylo** [comment]
Leave the diacritics in your letters_pt_BR file. This will mean they end up on the board. Thanks for leaving a comment on #71, once we change Lexica's guts to allow words to be chosen without diacritics, then we have a reference that pt_BR cares about this too.
