### ISSUE TITLE
Extra thrill: colorize letters towards the end of the game

### ISSUE THREAD

**Issue by frief** [lexica/lexica#13]
It would be nice, if, a while into the game, the letters would get a slightly different color according to their relative importance (as the first letter of the left over words).

I'd propose an option to colorize the letters when only 1/e = 0.368 of the overall time is left.

Only one fraction to make things still comparable.
Rationale for that strange number: if 0.5 were chosen (another reasonable choice) then the quest falls into two equal parts and players might start to (relatively calmly) wait for the convenient help in the second phase (no extra thrill). With markedly less then 0.5 you still wait for the second phase but then as you know it's significantly shorter the thrill does not slacken (end sprint). 1/e is the natural choice below 0.5:)

No soft blend-in on purpose (would be distracting because colors instead of letters would get attention and would be display/environment dependent anyway).

Colorizing green would calm things down too much for my taste, red would be nice but pretty aggressive, grey is not overly inspiring:)

It might be tempting to have the fraction as a tunable but please don't offer it like this (fragments users community and moves attention to tuning the game).

Instead address the need with a button like "add 60s [to countdown]".  Use 60 s not 1 min to avoid the vagueness of a minute:)

That button adds the extra emotional aspect of wanting to be helped/not wanting help/little cheating/no cheating to the game. Simultaneously it allows the user to have a valve for stress if he/she wishes to.

Sorry for using imperatives like "use" or "address" - they helped me to lay out the ideas.

Greetings,
Frieder

**Comment by pserwylo** [comment]
Thanks @frief, again I appreciate the input. I think this is a pretty valid thing to suggest. At this point, I think I personally would rather have the other two things you suggested implemented in the game - but always happy to receive pull requests. I'd include this only if it was either:
 * A preference which can be enabled (allow people to configure all the things), or
 * A new mode, so when starting a new game, there is "Classic" mode and "Easy" mode or something like that.
I think the second is probably preferable, because that allows for:
 * More modes to be added in the future.
 * Although I think it is important to allow things to be customized, adding a new preference for every new awesome feature can get out of hand quite quickly.

**Comment by pserwylo** [comment]
I'm going to close this now, as there is a manual option to enable "Hint mode" that will be added to the next release. It isn't exactly what is described here, but it serves a similar purpose.

I still look forward to the idea of introducing "modes" instead of adding a new preference for everything, as per my comment above, and hopefully we'll get some time to work on that in the future.
