### ISSUE TITLE
[FR] new mode: letters in a circle

### ISSUE THREAD

**Issue by ildar** [lexica/lexica#133]
the existing game implements something quite close to Lexica: https://www.youtube.com/watch?v=U68lYUA4Dj8
with a little difference: you can use any letter on the table in any order. This allows to find longer words which makes the game more interesting.

**Comment by pserwylo** [comment]
Hi @ildar - I've started work on the wiki (yay!) but also made a list of proposals that are out of scope because they would require too many changes to the core of Lexica. This mode would fall into that category, though I'd encourage anybody to fork Lexica should they wish to make a variant with different layouts like this.
