### ISSUE TITLE
Word path trace no longer visible in 1.0.0

### ISSUE THREAD

**Issue by kuba-orlik** [lexica/lexica#157]
In previous versions when dragging a finger on the board, the tiles that were already touched during that drag were highlighted, so it was easier to see which letters can still be used and if the gesture registered as intended. 

In 1.0.0 the trace is no longer visible, adding a little bit of frustration to the UI

**Comment by pserwylo** [comment]
Oh, thanks for reporting. I haven't experienecd that myself, could you please let me know whether this is in Dark mode or Light mode, and perhaps some other info such as what version of Android you are running? Does it happen if you change some of the settings (e.g. board size, score type, etc?). Thanks.

**Comment by RustanHakansson** [comment]
I just installed 1.0.0 (through F-droid) and I can see the path in both light and dark mode. On Android 7.1.2. 

Related note: There is no way to see the app version from within the app. Suggestion: Add that to the bottom of the settings list.

**Comment by kuba-orlik** [comment]
Oh. I'm using a monochrome filter on my phone so everything is in b&w (enabled in developer settings). 

After disabling it, I can confirm that the trace does in fact appear as expected.

When monochrome filter is enabled, the trace is not visible in light mode, but it is visible in dark mode.

I think the issue is, then, that the color of the trace in the light mode has similar lightness to the background color and because of that it isn't differentiated when the b&w filter is enabled.

**Comment by pserwylo** [comment]
Ah, haha. Thanks for clarifying @kuba-orlik. I am going to close this issue, because the light filter isn't necessarily designed to be accessible, just aesthetically pleasing for the most part. Indeed there is discussion in #97 about the contrast of the light theme, but we decided against making it higher contrast because the dark theme is available for that.

Perhaps I'll experiment with a "high contrast" theme just for fun, but also accessibility.

**Comment by pserwylo** [comment]
For anyone interested, there are some screenshots in #165 of the new high contrast theme :)
