### ISSUE TITLE
How current is the new dict instructions?

### ISSUE THREAD

**Issue by RustanHakansson** [lexica/lexica#175]
I want to add Swedish language dict. How current is the instructions for adding new ones? There are a bunch of issues about maybe switching dicts, is it better to help out with that first, before adding more? Or would much of the work remain valid after switching dicts, so might as well do that now?

**Comment by pserwylo** [comment]
Oh great, that would be wonderful.

> How current is the instructions for adding new ones?

The instructions at `[assets/dictionaries/README.md](https://github.com/lexica/lexica/blob/master/assets/dictionaries/README.md)` are extremely current, having been written and updated with the recent addition of the `pt_BR` dictionaries.

> There are a bunch of issues about maybe switching dicts, is it better to help out with that first, before adding more? Or would much of the work remain valid after switching dicts, so might as well do that now?

These all pertain to the choice of wordlist. The wordlists used for most languages are a straignt dump from the `aspell` tool (indeed that is the first step in the instructions linked above - and if you have a good wordlist handy, then just skip that step). This is because I have no experience in other languages, but I still wanted to offer a playable experience to as many people as possible.

If we have a good quality wordlist for the Swedish language, with appropriate licensing, then it is ready to go. Indeed if that is the case, then we can also mark the language as non-Beta. "Beta" is my terminology for "@pserwylo, with no language-other-than-English experience, has added a dictionary, and has no way to vouch for whether it is any good or not". If a native speaker says that the wordlist is good, then no need for beta.

**Comment by pserwylo** [comment]
FYI @RustanHakansson - when adding languages, the step about "analyseLanguage" which is used to generate letter probability distributions was accidentally broken with the new gradle files lately. I've fixed this in #191.
