### ISSUE TITLE
Where are the letter distribution files?

### ISSUE THREAD

**Issue by RustanHakansson** [lexica/lexica#184]
I cannot find the letter distribution files per language in the code, where are they? 

I looked at this letter distribution in many languages:
https://en.wikipedia.org/wiki/Scrabble_letter_distributions
and wanted to compare how that looks with the currently implemented languages. If there was a structure that could be identified, then maybe I could use that list as a base for generating letter distributions for all the languages in the list, reducing a step needed for adding new languages later.

**Comment by pserwylo** [comment]
They are in the `app/src/res/raw/letters*` files (check out the most recently added for one with comments: https://github.com/lexica/lexica/blob/master/app/src/main/res/raw/letters_pt_br.txt). 

They will not be of much use though, because they were generated by a genetic algorithm which optimises for boards with a "good" amount of words.

The documentation for the format is [here](https://github.com/lexica/lexica/blob/master/assets/dictionaries/README.md#anatomy-of-a-random-board-generator-in-lexica) (I reverse engineered the meaning from the original Lexic game, and didn't make any changes as it seems to work well).

The genetic algorithm which produces these files can be run using `gradle analyseLanguage_en_US`, but I only realised yesterday that this was broken with the recent bump of gradle and other tools, so we'll need to look into it.

**Comment by RustanHakansson** [comment]
Ok, thanks! If it would be better to have the letter distribution pre-made and based on scrabble, I could do the work for converting all the languages on that WP page to a usable format.
