### ISSUE TITLE
Allow for multiple dictionaries

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lexica/lexica#2]
```
At this point, the code for creating and using dictionaries is written in
such a way that only the US and UK dictionaries are easily supported. 
Rewriting some code to add support for more dictionaries would solve the
problem.
```

Original issue reported on code.google.com by `rev.n...@gmail.com` on 24 Feb 2009 at 7:11

**Comment by gabsoftware** [comment]
Please... Add support for more dictionaries. Custom dictionary support would be awesome.

**Comment by pserwylo** [comment]
@gabsoftware, thanks for you're interest. This is something that I'm quite keen on getting working when I have time. I've started working on the code to slowly migrate to a point where we can implement different language dictionaries, but it wont happen immediately because it involves quite a few changes. Some of those changes are already done, others will come in the future. Keep an eye on this issue and I'll update it in the future.

**Comment by pserwylo** [comment]
Closing in favour of #27 which has more detail and doesn't include the Google Code Exporter junk.

**Comment by wydoo** [comment]
Hi! What is the difference between words.bin and dictionary? I cannot figure it out? Which one is used for what?

**Comment by pserwylo** [comment]
`words.bin` (which is now language specific `words_LANG.bin` are binary data structures that contain an entire dictionary in a compact fasion, known as a "trie". This is to allow efficient iteration of 10s of thousands of words on devices with low processing power. The dictionary is the source file which is used to produce the `words.bin` file using some preprocessing scripts available in this repository.

**Comment by wydoo** [comment]
@pserwylo cool, thank you. Is there any nice way  / tool to edit these trie files? (I guess I have to mount the bin file to make it accessible). I'm asking because I lack many words from the HU one and I would like to add more.
