### ISSUE TITLE
Adding Santali Language

### ISSUE THREAD

**Issue by Prasanta-Hembram** [lexica/lexica#208]
Hi, I have translated Lexica in Santali language in Weblate. But after that how to get into the dictionary. I am unable to do it. I need help in adding dictionary for Santali. Thanks

**Comment by pserwylo** [comment]
Thank you very much for the translation. In order to add a dictionary, you'd need to first have a freely licensed word-list ready, and then you can work through the documentation here for the code changes required to add a new language (unfortunately it is not as easy as translating string in the app):

https://github.com/lexica/lexica/blob/master/assets/dictionaries/README.md
