### ISSUE TITLE
Exclude unstable versions from being picked up by F-Droid

### ISSUE THREAD

**Issue by rugk** [lexica/lexica#214]
As https://github.com/lexica/lexica/issues/211 showed, it's bad when F-Droid picks up alpha versions.
AFAIK these can be excluded from F-Droid's build process.

See https://f-droid.org/en/docs/FAQ_-_App_Developers/#what-about-versioning

**Comment by pserwylo** [comment]
Thanks @rugk. Indeed this is bad. I only realised it after the first alpha was already built (see the [fdroidata merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7814#note_459595968)).

I'm really looking forward to this being supported in an automated fashion via [fdroidserver#161](https://gitlab.com/fdroid/fdroidserver/-/issues/161), however until then we need to change the [com.serwylo.lexica.yml F-Droid build metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/5c74cbc9/metadata/com.serwylo.lexica.yml#L171) to only automatically pick up only stable releases. Right now it picks up any tag prefixed with `"v". A quick look at other apps shows people seem to get around this by being more explicit with their tagging to include a suffix such as `"-fdroid"` or `"-release"`.

I think a suffix of `v2.0.0-release` is nice, because it will be super explicit to anybody browsing the repository that these tags are releases. Then we can have `v2.0.0-alpha1`, `v2.0.0-alpha2`, etc, `v2.0.0-release`.

**Comment by pserwylo** [comment]
Closing this as I tidy old issues, because the F-Droid tools do not yet support it, and also I don't plan on having many more alpha versions. The new UI called for alpha, but from now I don't see any major changes like that happening again. If it does, I'll think carefully about how to tag alpha's.
