### ISSUE TITLE
Min word length doesn't work as expected

### ISSUE THREAD

**Issue by krushia** [lexica/lexica#215]
Create a new game mode with 5x5 board and min word length 3. Words with 3 letters will not be accepted.

Same with 6x6 boards and min word length of 3 or 4.

**Comment by ChildishGiant** [comment]
Also I'd expect attempts of length less than the min to not come up at the bottom. This would stop one letter taps appearing at the bottom.

**Comment by pserwylo** [comment]
Thank you very much for reporting this @krushia, it is indeed a silly bug. I have pushed a fix in PR #218 and when F-Droid builds and releases v2.0.0-alpha3 it should be resolved.

**Comment by pserwylo** [comment]
@ChildishGiant - interesting call. Could you please open a new issue for this as I'd like to close of the bug relating to min word length not working at all. Some things that come to mind:
* I like the idea of not filling the "found words" list with inelligible length words
* This would be a big win for modes with a small "Min word length"
* For modes with larger lengths (e.g. 6 words), they can become quite difficult. Once you've spent the time to construct a 5 letter word that is *almost* counted, then it can be helpful to be able to see the word you just missed out on.
* I wonder if there is a happy medium? Maybe just always leave out 1 + 2 length words regardless, because no game mode will ever accept them, and there is not a lot of useful information in them to help you progress, they will always be just noise.
