### ISSUE TITLE
Editing or Deleting Game Modes

### ISSUE THREAD

**Issue by antidaeophobic** [lexica/lexica#219]
There is no way to edit or delete a custom game mode. If the user makes a mistake when setting it up, they have no way to rectify this without creating a new game mode.

**Comment by pserwylo** [comment]
Great call, I was just thinking this today as I was testing this alpha version.

Quick question, what is the best way to do this? I am happy for a "Delete", but not so sold on "Edit". Specifically, if you have a bunch of high scores for a particular mode, then you edit it to make it easier, what happens to the high scores?
 * Does it warn you about losing high scores, then allow you to edit?
 * Does it instead ask you to delete and then recreate it?

Happy for feedback from those of you in the community as to the best way to approach this.

Another question worth asking - what is the best UI for this?
* If there is no edit functionality, then perhaps a long press on the game mode opens a menu, of which one item is "Delete" with appropriate warnings.
* If there is an edit mode, then next to the save button can be a delete button (again with warnings).

**Comment by antidaeophobic** [comment]
To be honest, I didn't consider what would happen to high scores, as I was only thinking of the use case where someone chose the wrong settings and wished to rectify it immediately. Only having the option to delete a gam mode would probably be the easiest way.

**Comment by pserwylo** [comment]
Thanks for the quick feedback. I'll make sure to get that implemented before a stable v2 of Lexica.

**Comment by pserwylo** [comment]
Alright, I have a work in progress which I'll push for release once I have a fix for #221 (a bit more critical, whereas this is still important, but a nice to have in comparison to critical crashes upon standup!).

The work in progress allows to long press on a game mode, and when doing so, immediately prompts:

> Delete custom game mode "XYZ"? Any high scores will be lost.
>
> \[Cancel\]      \[Delete\]

I could have implemented an intermediate popup menu which has a single option, which at this point is "Delete", but seems unnecessary. It would be easy to implement should we wish to include more options in the future.

The only improvement could potentially be to replace the long press with a toolbar delete icon, because that would be much more discoverable. My only annoyance with that is that the delete and add-new button would be alongside each other, and one applies to the selected item and is destructive whereas the other is the addition of a new item.

**Comment by antidaeophobic** [comment]
In terms of discoverability, perhaps the more intuitive solution would be to have a 3-dots menu (which is apparently called a kebab menu) on the side of custom game modes with the option to delete. This would increase visibility of the option, and would also serve to highlight which game modes are default and which are custom.

**Comment by landry314** [comment]
swiping left with a confirmation trash can to tap could work. or a long press then confirmation delete. deleting modes is all you need. editing gets messy because of high scores. just create a new mode and delete the old one if you want to edit.

**Comment by pserwylo** [comment]
Thanks for all the feedback everyone. I've stuck with the "long press to delete" for now even though I agree it is not the best user experience. Just keen at this point to have **something** rather than nothing. Will happily accept pull requests with alternative and improved user experiences.
