### ISSUE TITLE
Crash on opening 

### ISSUE THREAD

**Issue by ClementEstievenart** [lexica/lexica#221]
All Lexica v2 pre-release crash when I try to open the app. 
Lexica v1.1.0 (latest release) work properly. 
I'm running Xiaomi No Note 10 Lite on Android 10 

The error log: 

```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter language
	at com.serwylo.lexica.db.ResultRepository.findHighScore(Unknown Source:7)
	at com.serwylo.lexica.MainMenuActivity.lambda$load$7$MainMenuActivity(MainMenuActivity.java:126)
	at com.serwylo.lexica.-$$Lambda$MainMenuActivity$034F0fTih04RzSV0E_Hm0ZJa6G8.run(Unknown Source:2)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by pserwylo** [comment]
Thank you so much for the stack trace, that will really help narrow this down. I'll see if I can figure out what is going on here.

**Comment by Eaglechild** [comment]
I have the same behavior on Samsung Galaxy 9 with /e/OS based on Android 8., the same error in the log. Thanks so much for your work, pserwylo! I would be glad if I could play the new version!
Regards

**Comment by pserwylo** [comment]
Hey @ClementEstievenart + @Eaglechild, just looking at this now. Could I ask if you are able to see any further context in the log?

This is my first time using Android Room to manage databases, so I struggled a little with the original initialisation of the database, particularly because I care a lot about maintaining everyones hard earned high scores during the migration.

Here is the main process:
* [Try to get the "current game mode"](https://github.com/lexica/lexica/blob/master/app/src/main/java/com/serwylo/lexica/MainMenuActivity.java#L121) (may return null)
* If it returns null, [then run the initial migrations](https://github.com/lexica/lexica/blob/master/app/src/main/java/com/serwylo/lexica/db/migration/MigrateHighScoresFromPreferences.kt#L15) (these have a lot of log entries using the tag `MigrateScoresFromPrefs`).
* After running the migrations, we [assume that there is now a game mode available](https://github.com/lexica/lexica/blob/master/app/src/main/java/com/serwylo/lexica/db/GameModeRepository.kt#L19) (obviously incorrectly!!)

So the logcat entries of interest are:
* From the migration (logcat tag `MigrateScoresFromPrefs`):
** ["Creating default game modes."](https://github.com/lexica/lexica/blob/master/app/src/main/java/com/serwylo/lexica/db/migration/MigrateHighScoresFromPreferences.kt#L23)
** ["Inserting game mode: ..."](https://github.com/lexica/lexica/blob/master/app/src/main/java/com/serwylo/lexica/db/migration/MigrateHighScoresFromPreferences.kt#L27) (don't need to worry about the other entries regarding migrating game modes from old lexica, because our issue here is that there seems to be *no* modes - not even default ones).
* From the game mode repository (logcat tag `GameModeRepository`):
** ["No current game mode stored (perhaps first run?)"](https://github.com/lexica/lexica/blob/master/app/src/main/java/com/serwylo/lexica/db/GameModeRepository.kt#L23)
** ["No game modes present, expected at least one so we could remember that as the current mode"](https://github.com/lexica/lexica/blob/master/app/src/main/java/com/serwylo/lexica/db/GameModeRepository.kt#L27)

The last one (No game modes present) should be present, because I believe that to be the root cause of the `NullPointerException` reported above.

**Comment by Eaglechild** [comment]
@pserwylo Oh dear... I have zero experience in android developing...
Thanks for looking into this.
So I installed the old version, played one game, updated and tried to open the new version. I connected the phone to the laptop with adb, ran adb logcat and captured the output in a file. From there I extracted everything with the pid of the process of the game. I will try to attach the file. Hope this helps. If you need more information, I will try to provide it, but I will need some help with the respective adb commands.
[lexica_catlog.log](https://github.com/lexica/lexica/files/5781286/lexica_catlog.log)

**Comment by ClementEstievenart** [comment]
I have something new : when I update Lexica from v1, v2 work. But the app crash when i install directly v2 on my phone.
My log :

                            Process com.serwylo.lexica created for activity {com.serwylo.lexica/com.serwylo.lexica.MainMenuActivity} caller=com.miui.home
                            PID: 31257   UID:    GIDs: 

         .serwylo.lexic  E  Not starting debugger since process cannot load the jdwp agent.
                   Perf  I  Connecting to perf service.
          FeatureParser  I  can't find toco.xml in assets/device_features/,it may be in /vendor/etc/device_features
        .serwylo.lexica  W  type=1400 audit(0.0:101591): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=20033 scontext=u:r:untrusted_app_27:s0:c106,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0
                   libc  E  Access denied finding property "ro.vendor.df.effect.conflict"
                   Perf  E  Fail to get file list com.serwylo.lexica
                         E  getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
                         E  Fail to get file list com.serwylo.lexica
                         E  getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
                         E  Fail to get file list oat
                         E  getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
        ForceDarkHelper  D  updateByCheckExcludeList: pkg: com.serwylo.lexica activity: com.serwylo.lexica.MainMenuActivity@adbba76
                   Util  D  Searching for lexicon that best matches the locale: "fr_FR"
                         D  Found matching language code "fr". Will now check country code.
                         D  Remembering language "fr" in case we don't find any better match.
        ForceDarkHelper  D  updateByCheckExcludeList: pkg: com.serwylo.lexica activity: com.serwylo.lexica.MainMenuActivity@adbba76
                   Util  D  No exact match, so the best option is matching language code with no specific country: "fr"
     GameModeRepository  I  No current game mode stored (perhaps first run?). Choosing the first game mode from the list of modes.
                         I  Remembering the current game mode: Game Mode [id: 1, type: SPRINT]
        ForceDarkHelper  D  updateByCheckExcludeList: pkg: com.serwylo.lexica activity: com.serwylo.lexica.MainMenuActivity@adbba76
         AndroidRuntime  E  FATAL EXCEPTION: AsyncTask #1
                         E  Process: com.serwylo.lexica, PID: 31257
                         E  java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter language
                         E      at com.serwylo.lexica.db.ResultRepository.findHighScore(Unknown Source:7)
                         E      at com.serwylo.lexica.MainMenuActivity.lambda$load$7$MainMenuActivity(MainMenuActivity.java:126)
                         E      at com.serwylo.lexica.-$$Lambda$MainMenuActivity$034F0fTih04RzSV0E_Hm0ZJa6G8.run(Unknown Source:2)
                         E      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E      at java.lang.Thread.run(Thread.java:919)
                 chatty  I  uid=10362(com.serwylo.lexica) .serwylo.lexica identical 1 line
        ForceDarkHelper  D  updateByCheckExcludeList: pkg: com.serwylo.lexica activity: com.serwylo.lexica.MainMenuActivity@adbba76
                   Util  D  Searching for lexicon that best matches the locale: "fr_FR"
                         D  Found matching language code "fr". Will now check country code.
                         D  Remembering language "fr" in case we don't find any better match.
                         D  No exact match, so the best option is matching language code with no specific country: "fr"
                Process  I  Sendig signal. PID: 31257 SIG: 9

**Comment by Eaglechild** [comment]
@ClementEstievenart, @pserwylo 
Thanks, ClementEstievenart for this comment! When I read your description, I remembered, that I never explicitly chose a lexicon before but used the default one. So I started the process again:
- uninstalled not working version 2.0.0-alpha3
- installed old version
- chose lexicon en_us
- played one game
- closed app
- updated from f-droid to version 2.0.0-alpha3
- now the game works!
I wanted to extract the log for this new installation, but I can't find any new entries in the logcat concerning the game. Is this perhaps  because there is no error?
I will also try this procedure with my other devices and post update.

**Comment by Eaglechild** [comment]
@ClementEstievenart @pserwylo 
So I tested some more.
Version 2.0.0-alpha3 only works, if I install version 1, explicitly select a lexicon and then update.
It does **not** work, if I install version 1 and play with the default lexicon, (apparently one of the English ones) and update. It does also not work if I directly install the new version without upgrading from version 1.
So it seems to me, that the new version looks for a previous version with an explicitly chosen lexicon in order to apply it with the update. If there is no previous version with a chosen lexicon, the game crashes, regardless, whether it was an update or not.
I hope, this helps for debugging. In any case, I can play the new version now -- which is great, by the way! But people who never had the old version on their devices or never chose a lexicon will probably experience the crash.

**Comment by pserwylo** [comment]
Found it! Devices with French and German locales will crash when trying to find a sensible default language to use for the game. Extremely reproducible when I set my device locale to one of these two languages.

Thanks so much for these logs all. I was so worried with my introduction of the database to the code base that I assumed that was the issue here. Especially as the line reported in stack traces refers to a game mode object which should be in the database but may not be if I broke something.

_However_, the other thing on that line of code is the language to be used for the game. I've only tested the first run experience using the locale my phone is set to (English), and as such didn't notice it was actually broken for French and German.

This is due to a broken assumption that the system locale is identical to the "name" of the language in Lexica. This assumption was broken for fr + de, because there we end up with a "locale" of fr_FR or de_DE, but a "name" of fr or de. Whilst it may be worth discussing the merits of this further, I've actually opted to just fix the broken assumption and returned the correct language.

I'll do some final testing, then bump v2.0.0-alpha3 to be built by F-Droid.

Thanks again!
