### ISSUE TITLE
How to shuffle/rotate board?

### ISSUE THREAD

**Issue by a123qwertz567** [lexica/lexica#229]
I did not find a better place to ask this...

Is it the desired behavior that the board rotates only around the same letter and the relative position of all letter stays the same?

If yes, is it possible to shuffle the board? 

I am not sure if I can find 100+ words in my current board situation.... :(

**Comment by pserwylo** [comment]
Here is perfectly find to ask questions, thanks for coming along. 

You are correct about the desired behaviour of rotating around the same letters, maintaining relative positions. The reason we don't shuffle the board entirely is because once shuffled, the entire list of available words would change again. This would break the notion of what it means to get a high score for a particular board.

As for finding 100+ words - don't worry, I've never finished a board and I've played this game since 2009! The dictionaries have always included just a few too many weird words. I think it would be nice to have some dictionaries such as "Top 1,000 words in the English language" or [something like that|https://xkcd.com/thing-explainer/].

**Comment by a123qwertz567** [comment]
Thank you for the answer. Makes sense :)
I am quite angry how long it took me to realize that the rotation is no shuffle ;)
And yes some words are not even "real" words ;)
