### ISSUE TITLE
How do I change grid size and default time?

### ISSUE THREAD

**Issue by ccady** [lexica/lexica#286]
I used to be able to change the grid size and the amount of time in the preferences sections. Now I do not have those options anymore.

**Comment by pserwylo** [comment]
Hi !@ccady - to deal with the fact that there was an every increasing set of permutations and combinations in preferences (due to good features being contributed by the community) - the decision was made to move these into "Game Modes", which you can access from the main screen via the button in the top right corner which tells you your current game mode. In there, you can select from some predefined ones, or you can create your own.

It is still a little clunky to create your own if you just want to do it for a one off - happy to take suggestions on how to improve the UX there.

Some added bonuses of this work was a sensible high score system that has been added (each game mode maintains its own high scores - accessible by tapping the high score on the main screen). It also made Multiplayer invites (offline invites via SMS/QR code/etc) much simpler - because you can clearly invite someone to play a specific mode with you.
