### ISSUE TITLE
How do I open board from seeded link offline?

### ISSUE THREAD

**Issue by vi** [lexica/lexica#290]
I have a link like `https://lexica.github.io/share/?b=...&l=...&t=...&...`. I suppose it contains seed and settings to replay the same board again.

How do I apply it to Lexica offline, without going through Internet?

I expect multiplayer screen to have buttons to scan the QR code directly and another button to just enter URL manually (e.g. by pasting from clipboard), both working offline.

Tried version Version 3.3.0 from F-Droid.

**Comment by pserwylo** [comment]
So this may differ depending on how your device is setup, default browsers, etc.

We have [setup Lexica so that it intercepts requests to `https://lexica.github.io/share/...`](https://github.com/lexica/lexica/blob/master/app/src/main/AndroidManifest.xml#L55-L64) and should thus prompt users if they want to open the link in a browser or in Lexica.

On my devices, this shows a prompt, asking if I'd always like to open in that app, so if I select "browser" and "always" then it never goes to Lexica. To address this, I can either:
* Change the default app settings using the device settings (depends on device and manufacturer as to how you clear defaults), or
* Ask your browser to launch the URL via an app (i.e. Lexica). In Firefox, it used to show a little android icon in the address bar you could tap to launch in an app if there was a supported app. Now it is buried in the Firefox menu as "Open in app". Not sure about Chrome or other browsers sorry.

**Comment by vi** [comment]
Indeed, as I select the link, Lexica is one of actions in the selection menu.
Forgot that it's possible for `https://` links, expected it to work only for custom schemes.
