### ISSUE TITLE
a voting system is necessary for the results page.

### ISSUE THREAD

**Issue by bennypr0fane** [lexica/lexica#295]
When the game is over, we can view the words that weren't found. At least in German, I guesstimate that at least 80% are not actually German words or plain don't exist.
Is the dictionary 100% scraped from Wiktionary? That site apparently features a lot of names marked as German words, among other oddities.
With Wiktionary being the reference for words used in Lexica, I believe we can't make Wiktionary better, but include a feature for downvoting words as non-words of the played language.
With a set number if downvotes, you could flag words for removal from the dictionary, and auto-remove them with a higher set number of down votes.
Also consider up votes to validate existing words - possibly only for words that already received down votes.
Right now, I consider the game hardly any fun because of the large percentage of non-words (again, this regards only German)

**Comment by pserwylo** [comment]
Thanks for the comments. I will preface my response with: I am not a German speaker, but I will always try to take on as much feedback from those in the community who are.

Voting would be a nice solution to some of these problems, but it of course brings other issues with it. Some of them are technical (providing a server to collate responses), some of them are privacy related (likely requiring accounts or recording device ID's in order to stop multiple votes), and some social (who do you trust?).

Given the project is a community run game with limited resources (both human and monetary), and given the points above - I'll have to say thanks for the recommendation, but now will not be the time to implement this.

For that reason, I'll close this issue, but I'm still very keen on more feedback in this thread if you are able to provide it.

I'd like to probe a little further with regards to the quality of the German dictionary. The reason is, this is one of the few dictionaries for which Lexica has a suitable source - https://github.com/enz/german-wordlist (see #69 for some of the old discussions around this). This is not even the case for my native English (e.g. I haven't gotten around to investigating #58 properly), which uses a dictionary of unknown provenance. There has even been further work from those in the community on providing both dictionaries with diacritics and those without. Also, a little work has been done lately with regards to improving the dictionary even further (see the recent #276) - though there is still improvements (e.g. #283).

**Comment by bennypr0fane** [comment]
I am a native speaker of German, a linguist, and my vocabulary is pretty decent. The last map I played using the AARD2, I managed to find three words, it was worse than the previous one using Wiktionary. Then I tried English, which is not my native language (learned at school) and found twelve words.
I took a look at the list of German words and noticed a lot of them are 2nd person singular (ending in -st) verbs. Some correct, but several also wrong, i.e. nonexistent - these wrong ones also didn't find a hit in Wiktionary. I suppose that might be one simple way of eliminating false words from the dictionary: by checking them against Wiktionary first.
I wonder though how those got there in the first place, and my guess is someone conjugated them using an algorithm instead of actual forms - an approach that can only result in mayhem in any natural language.
One pretty easy way to eliminate a lot of these problems would be to simply not admit any inflected forms of anything (indeed I would specifically make the same case for plurals in English), in the name of playing fun. I submit that finding every possible inflexion of a given word is much less fun than finding a new word. After all, this game is about fun with words, not mathematics, I assume.
Players never think of inflected forms in common word games like cross words (unless maybe specified that e.g. a plural form is wanted). And inflexion especially of verbs gets ugly, quickly - in most languages.
Also, proper names are an issue IMHO, because there's just no way of cleanly separating the more outlandish (i.e. foreign to speakers of that language names from those familiar to the average. I suppose you could with largest capitals where those languages have most speakers, well-known field names in general - but here already we're going down a rabbit hole too deep for community-driven game.

**Comment by Morphior** [comment]
@bennypr0fane I mean, we could try to create an “ultimate” German word list which is basically a CSV or JSON and has every word along with a bunch of “metadata” about said word, for example the corresponding root word, whether it’s a root word itself, etc. Hit me up if you want to give this a shot, I’d be all for it.
