### ISSUE TITLE
Min-length words count as "missed words" but not as "found words"

### ISSUE THREAD

**Issue by TZeeGithub** [lexica/lexica#306]
Lexica v3.5.0, installed via F-Droid.

Playing on a 4x4 board with min word length 3, scoring type "word length".

After a sample game, it reports 22 of 54 words found.

The Found Word list contains *48* words.  26 of those are 3-letters words and have a "+0" score value.  22 of those words are 4 or more letters.  I.e. only words of *4+* letters are counted as "Found".

But the Missed Word list contains the expected 54-22 = 32 words, including many 3-letter words, and in this list they have a "+1" score value.

So 3-letter words that I find do NOT count towards my score, but 3-letter words that I miss DO count AGAINST my score.

![FoundWords 01-13](https://user-images.githubusercontent.com/75507292/147892362-ef82e635-82f6-4288-9b20-fb528bc410b1.png)
![FoundWords 14-26](https://user-images.githubusercontent.com/75507292/147892364-cae564fd-4b9f-4822-a529-b95c21ea73d2.png)
![FoundWords 27-39](https://user-images.githubusercontent.com/75507292/147892365-c2614938-74fd-48fb-b8ef-8c2a7ac641b9.png)
![FoundWords 34-48](https://user-images.githubusercontent.com/75507292/147892366-a3da9754-192f-4ebb-86d7-96a5d2582697.png)
![MissedWords 01-10](https://user-images.githubusercontent.com/75507292/147892368-f3007ef7-1b5d-4bec-b420-8be3ab5c3ea3.png)
![MissedWords 11-20](https://user-images.githubusercontent.com/75507292/147892369-87b24fb6-67a5-478a-bc30-92b9d5c32d4d.png)
![MissedWords 21-30](https://user-images.githubusercontent.com/75507292/147892370-8c45b808-9f2a-40d2-b82b-bad0e8aeef71.png)
![MissedWords 23-32](https://user-images.githubusercontent.com/75507292/147892371-b7076bde-ab75-416e-8383-9cff4186521a.png)

Thanks for taking a look at this.

**Comment by pserwylo** [comment]
Hmm, thanks so much for the detailed report and screenshots @TZeeGithub.

I think this is a UX issue that needs fixing. I had to try a few times before remembering what the UI is actually telling us:

The "Found Words" is not just things which were found *and actually words*, but rather all words that you selected during the game, even those which are not words (hence the score of "+0"). 

We have two options:
* Only show words which are actually words (which lines up with the actual terminology of "Found Words")
* Properly fade and strikeout those which are not words (which mimics the UX during the game, and still tells the player what they selected so that they can learn from their mistakes - this should also remove the "Define" button - because there is no point trying to view the definition of a word which is not a word).

I think I will implement the second one because I have always found it helpful to be able to review the crazy attempts at words I selected.

**Comment by pserwylo** [comment]
Haha, I had a little chuckle when I went to the code to check it out and found a comment from past-me saying: `TODO: Ah... what?` and a commented out `/*selected.isWord*/`. Oh well, at least it should be straightforward to address :)

![image](https://user-images.githubusercontent.com/248565/147927934-7adad331-7309-4ab1-b1a3-1128ad1ff636.png)

**Comment by pserwylo** [comment]
Haha, and it just gets worse - looks like I half-did this in the past but never actually turned the feature on (due to the commented out `/*selected.isWord()*/ above!

https://github.com/lexica/lexica/blob/master/app/src/main/java/com/serwylo/lexica/activities/score/ScoreWordsViewBinder.java#L130-L144

**Comment by TZeeGithub** [comment]
@pserwylo  Heh!  Looks like a test-driven approach ("write the test case first, see it fail, then make it pass") was called for  :-)   (just joking, not criticizing)

Yes, I should have noticed the +0 words were not valid words -- I let the "Found Words" header mislead me.  Your 2nd option sounds good.

Thanks for the super-fast follow-up!

**Comment by pserwylo** [comment]
Most of the code in place worked as expected (hiding the score and removing the "define" button for such words). I just tweaked it to also change the font style to match that used in the game:

![image](https://user-images.githubusercontent.com/248565/148202087-8d24bb19-6786-4561-a772-31cfb5fdbce0.png)

I'll get this committed and when I tag a release I'll comment here (it will take F-Droid a few days to a week to build after that).
