### ISSUE TITLE
Dutch letter distribution

### ISSUE THREAD

**Issue by Sjord** [lexica/lexica#307]
The [Dutch letter distrubution letters_nl.txt](https://github.com/lexica/lexica/blob/master/app/src/main/res/raw/letters_nl.txt) is not well balanced. It favors about seven letters: a e k l n s t. Many other common letters are rarely picked, especially d, f, v, w, z.

The result of this is that the game is played with a small subset of the alphabet, and the same words keep appearing. The game would be more fun with more letters and more variation in words.

I think this is a side-effect of optimizing for a small variance in the [genetic algorithm](https://github.com/lexica/lexica/blob/master/libraries/language-analysis/src/main/java/com/serwylo/lexica/language/GeneticAlgorithm.java#L247). With the letters aeklnst is is possible to make hundreds of words, so that results in a large average. Having other commonly used letters increases the variance, so this is selected against. Letters that don't introduce new words reduce the variance, and that is why the diacritic characters and very uncommon characters such as x are rated relatively high.

I [created a letters_nl.txt](https://github.com/Sjord/lexica/blob/dutch-letter-distributions/app/src/main/res/raw/letters_nl.txt) based on letter distributions. The game doesn't become much easier or harder, but it does result in more variation in words and more fun.

Do you want to fix the genetic algorithm, or is it OK to deviate from that algorithm and modify the letters_nl.txt manually?

**Comment by pserwylo** [comment]
Thanks for the feedback and investigation.

In light of recent feedback from the community about particular languages (such as what you have provided here), I've been thinking that perhaps a genetic algorithm isn't the right choice. Or at least perhaps it shouldn't be as dominant vs a statistical approach that is based on letter frequencies within the given word list.

Regardless - please *do* send a PR with the manually tweaked `letters_nl.txt`. I'd much rather each language have attention from native speakers, rather than blindly following an arbitrary algorithm designed by an English speaker. Lets make this as fun as can be.

One request - newer files have auto generated comments at the top prefixed with `#` (e.g. [letters_pt_br.txt](https://github.com/lexica/lexica/blob/master/app/src/main/res/raw/letters_pt_br.txt#L1-L14)). Could you please add some commentary, perhaps even just linking to your detailed explanation above at the top of the newly updated `letters_nl.txt`?
