### ISSUE TITLE
CharProbGenerator only shuffles first 16 letters

### ISSUE THREAD

**Issue by Sjord** [lexica/lexica#310]
```
private String[] generateBoard(int size) {
    ...
    // shuffle the letters
    for (int to = 15; to > 0; to--) {
        int from = rng.nextInt(to);
        String tmp = board[to];
        board[to] = board[from];
        board[from] = tmp;
    }

    return board;
}
```

Even though it is possible to generate boards of 16, 25 and 36 letters, [only the first 16 letters are shuffled](https://github.com/lexica/lexica/blob/master/libraries/liblexica/src/main/java/com/serwylo/lexica/game/CharProbGenerator.java#L119-L125). The loop should probably start at `size - 1` instead of 15.

**Comment by pserwylo** [comment]
Whoops! Great catch! Apologies for not looking earlier, I am now tidying up as many issues as I can.

This went undetected because the letters are randomly selected before this shuffle. However, they are not *uniformly random*, but rather they were selected using roulette wheel selection so more common letters likely come first. Thus, fixing this *may* result in a slight change to the type of boards generated. In my testing, the change to the number of words on each English board was marginal. Nevertheless, any change here is for the better. 

Fixed in #363.
