### ISSUE TITLE
Request to add Turkish dictionary

### ISSUE THREAD

**Issue by bmusalli** [lexica/lexica#342]
Request to add Turkish dictionary

**Comment by pserwylo** [comment]
Thanks for the request @bmusalli. Could I ask if you have any time, could you please look over the following wordlist and let me know if it is suitable?

https://gist.github.com/pserwylo/b8c9d7a6ba26884702ad096594a4f297

Without verifying every single of the 38120 words in the word list, I was hoping you could take a moment to glance over a sampling of the words and let me know if you think it is suitable for a game like Lexica? For example, some languages end up with acronyms (e.g. ATM) in them, while others have proper nouns or hyphenated terms or other weird things which wouldn't make sense. If you are happy with the wordlist above (doesn't contain strange words for a word game like this), then I'd be happy to add that as the Lexica Turkish dictionary.

For reference - the reason it may be not-quite-perfect is because I generated it by asking my spell checker (GNU Aspell) do dump all of the Turkish words it knows about. Spell checkers are not perfect for wordlists, but they can provide a good starting point, and I know that the license of that wordlist is suitable for publishing with Lexica under the GNU GPLv3 license. Other wordlists online may not have compatible licenses.

**Comment by bmusalli** [comment]
Thank you very much for your return. I looked at the words and there is no
problem. I would be very happy if you add them to the game.
I tried to do it myself but I couldn't make it work.
have a nice day

4 Ekim 2023 Çarşamba tarihinde Peter Serwylo ***@***.***>
yazdı:

**Comment by pserwylo** [comment]
Great, I appreciate your quick response (more I can say for my very belated response - which I must apologise for - I'm now determined to get through a bunch of Lexica issues in the coming weeks).

If we continue the discussion, there is a couple of other things I'd like to ask about if it is not too much effort.

Firstly - there are 38120 words in the dictionary I linked you earlier. In all of the words, this is how many times each character appears:

```
  33257 a
   1049 â
   4730 b
   4494 c
   3590 ç
   5596 d
  21496 e
   2519 f
   2929 g
   4366 ğ
   3377 h
  18357 i
    457 î
  13758 ı
    397 j
  17524 k
  18835 l
  14208 m
  11013 n
   6907 o
   1855 ö
   3578 p
  15345 r
   8974 s
   4886 ş
  12206 t
   8213 u
    106 û
   5422 ü
   2755 v
   6607 y
   5181 z
```

Not all of them appear in the [Scrabble letter distributions for Turkish](https://en.wikipedia.org/wiki/Scrabble_letter_distributions#Turkish). Some of them appear so infrequently that it makes me think they may just be from loan words.  When I look at the wiki article for the [Turkish Alphabet](https://en.wikipedia.org/wiki/Turkish_alphabet), the following characters from my above list are **not** shown as part of the alphabet: `â, î, û`. Can you shed any light on these? Are they just from loan words and we can exclude words including them? Or do we need to keep them? If we remove them, that solves the scrabble letter scoring problem, because we now have "Letter scores" for each word in our dictionary.

Thoughts?

**Comment by bmusalli** [comment]
Yes, these letters are words borrowed from other languages, there is no
problem if we do not take these letters.
thank you for your interest

7 Ekim 2023 Cumartesi tarihinde Peter Serwylo ***@***.***>
yazdı:

**Comment by pserwylo** [comment]
Awesome. We are getting there. I have a playable version ready. The only quirk is with the letters ...

Notice how the board correctly shows the two upper case variants of the `i` character, and it also correctly shows the letter point scores as `1` and `2` as per the Wiki article on Scrabble letter scores. However, during end game scoring for whatever reason when it upper-cases the words in the word list, it shows them both as `I` (incorrectly). I think I'll release this version as it seems like a minor issue for now? (happy to be corrected) and I will log an additional issue here to track the quirk.

**Comment by pserwylo** [comment]
![image](https://github.com/lexica/lexica/assets/248565/2fd2cb09-a416-4294-837e-19dd16a174aa)

Oops, forgot the screenshot above.

**Comment by pserwylo** [comment]
Never mind, I found the fix. Wasn't correctly asking Java to use the Turkish locale when upper casing those letters:

![image](https://github.com/lexica/lexica/assets/248565/b1c07dcf-17d2-471c-a18e-b75e98f12a88)
