### ISSUE TITLE
Create user's own dictionary

### ISSUE THREAD

**Issue by 2013ZRZ** [lexica/lexica#380]
I hope **users can create their own dictionaries** in the future versions.

**Comment by pserwylo** [comment]
Hi there, thanks for stopping by with this feature request. I'll close this issue and direct you to #134. It doesn't have much activity - not because it is a bad idea, but because everything can be a bit slow moving around here. Pleaes go throw a :+1: on that issue so myself and others can know what the community would like prioritised in the future. Pull requests are also welcome, but if not, we will get to it eventually :)
