### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by mhabibi659** [lexica/lexica#65]
Hi, May I contribute for you? by designing a logo

**Comment by pserwylo** [comment]
Hey @mhabibi659, thanks for the offer. I'd be more than happy to consider any contributions. I can't promise that what you end up with will be adopted as the logo, but I can promise that it will be looked at seriously, with appropriate feedback.

If you're curious, this is the original logo used by Lexic (which this game is based on):

![image](https://user-images.githubusercontent.com/248565/39273977-d73247f8-4923-11e8-8ef3-2e72821ba434.png)

My first attempt at changing the logo resulted in this:

![ic_launcher](https://user-images.githubusercontent.com/248565/39274141-606e215e-4924-11e8-933f-a1c090223961.png)

I eventually updated this, because I wanted it to adhere to the material design specifications (https://www.google.com/design/spec/style/icons.html) which resulted in the current logo:

![ic_launcher-web](https://user-images.githubusercontent.com/248565/39274200-8add568a-4924-11e8-9c6a-394315a96ec1.png)

So I'd be hopeful that any subsequent logo would also adhere to those specifications. I'm happy to feedback on general sketches though, and we can worry about making it adhere to that specification later on.

The main thing I dislike about the current logo is the letter "L", because I'm putting in quite a lot of effort to make this an international game. For example, I'm just about to release a version which supports a Persian dictionary. The Latin alphabet is no longer the only alphabet used in this game, and thus using any specific letter is probably not appropriate.

**Comment by pserwylo** [comment]
I'm going to close this for now, but if you'd like to pursue some sketches, please just comment on this issue and we can re-open.
