### ISSUE TITLE
German dictionary isn't very good.

### ISSUE THREAD

**Issue by Bubu** [lexica/lexica#69]
Missing lots of common words: Bier, Blei, Gieb

**Comment by pserwylo** [comment]
Thanks @Bubu, nice to see you here too :)

Wow, can't believe we've missed out on Bier of all words!

Now that I have the infrastructure in place for arbitrary languages to be added, the next step is to find high quality word lists to use for each language. Currently I'm using the output of:

```
aspell -l de_DE dump master | aspell -l de expand | tr ' ' '\n' | grep -P "^\p{Ll}*$" | sort
```

Which is pretty sub standard in English also, so it is not surprising it is the same in German. In English, it comes up with many abbreviations, prefixes, etc. In German, this is the word list I've gotten from `aspell` (truncated to work lengths >= 3 and <= 9):

https://github.com/lexica/lexica/blob/master/assets/dictionaries/dictionary.de_DE.txt

If anyone German speakers are able to provide the source of a nice word list to use for German, then it can be incorporated into this game relatively easily and we can replace the `aspell`-based version. Please comment in this issue if you've found such a source, and it is freely licensed. For example, the English equivalent of such a word list would probably be http://wordlist.aspell.net/12dicts/ (#58).

**Comment by wichmann** [comment]
I have the same problem as @Bubu. It seems that all nouns are missing although they are present in the original word list.

The regex you're using in grep filters out all word with uppercase letters. In German all nouns begin with an uppercase letter. So they are missing from the word list. By allowing words starting with uppercase letters the problem should be fixed.

Would be really nice if this problem were fixed, because I really like the game! Thanks!

**Comment by wichmann** [comment]
@pserwylo - thanks for your quick reply. Overall I think the list looks fine. Because of your change all abbreviations are still included. I picked some examples and whether or not to include them:

```
ACL        -> no
ACLs       -> no
BGHSt      -> no
BTX        -> no
EnBW       -> no
Kfz        -> yes/no
kHz        -> no
KiB        -> no
Landebahn  -> yes
```

The best approach seems to check for uppercase letters "inside" words. All words that include an uppercase letter that is not in the first position should be filtered out. That would only leave proper names like "Wolfgang". But in German you can't distinguish them from other nouns.

I hope this helps...

**Comment by Mannshoch** [comment]
i use https://github.com/languagetool-org/ for spellchecking. the best i ever had used in linux. maybe it has a good dictionary to use.

**Comment by tinasfeedback** [comment]
There are letters in the german language (umlaute) that are missing so to speak, but you can generate them with two letters.

Ä --> AE
Ö --> OE
Ü --> UE
ß --> SS

So it would be great  if you could change these chatacters in the words from the dictionary somhow

Eg grün --> gruen

**Comment by pserwylo** [comment]
As always, thanks for all your feedback. @wichmann - I've done what you suggested and included words from GNU aspell which start with an upper case letter. This is the list of words which are added to the word list in response: 

https://gist.github.com/pserwylo/27019d0e12483a8ac227d95d802d37ac

That bumps the words from 60,000 words to 90,000 words, so I was mistakenly excluding a huge amount of words! If you give me the okay, I'll add these to the German dictionary and then release a new version. If you have any further feedback on these words or suggestions for how to further process them I'm all ears.

**Comment by pserwylo** [comment]
@Mannshoch - Interesting. I'll see if I can get a word list from them (e.g. using [the approach from here](http://wiki.languagetool.org/developing-a-tagger-dictionary#toc2)). if so, I'll compare it to the GNU aspell version currently in use and ask for feedback on this issue.

**Comment by pserwylo** [comment]
@wichmann  - Great, I'll keep the aspell wordlist for now, including nouns. 

As for the issue @tinasfeedback, I believe it is because I am converting each letter to upper case for displaying on the board. In the case of:

`"ß".toUpperCase()`, java will give us `SS`. I'll change that so for this letter it is kept as `ß`.

**Comment by Mannshoch** [comment]
I would convert ß into two separate S, But I'm here not the right Person to decide this. In Switzerland dictionary all ß are replaced by SS and we also do not have it on Keyboard. So words like Buße und Busse are written the same way. I would use the Rules in Crosswords. If German Crosswords use ß it should also been used here.

**Comment by Bubu** [comment]
I'm pretty sure German crosswords use ss exclusively. Also always ae, oe, ue instead of ä, ö, ü.

**Comment by tinasfeedback** [comment]
I'm using an andrioid version 7.1.1, lexica 0.11.1.
Sometimes the app crashes when starting a german game ( lexica was ended, open app again? Shows up, in german). I don't see any ä.ö or ü. I had a double s, but it did not work ( words that shoukd be in the current list did not register as such like i think  saß.

When i wrote the previous comment i did not think you would use ß,äöü as seperate letters, but i assumed, the player would have to put two letters together like a and e ( could then be ae or ä). Thats why i thought you would convert the word list first. That's how it is done in crosswords. I still think this wouldbea good option.

If you use the äöüß then i think a "ß" would be while theoretically wrong as uppercase the better choice as it is unambiguous (ss could mean ss after all, and that would be wrong, wouldn't it?)

I am not quite sure if i remember correctly, but i think you use qu on one stone in the english version?!! That wozld be the same in german, q normally comes with a u as in quasi, and virtually never without, as in qi.

Thanks you!

**Comment by wichmann** [comment]
@Bubu is right. German crosswords use ss, ae, ue, oe instead of ß, ä,ü, ö. So it makes sense to do the same here. Also with the double-character versions you get more possible words for each game. But IMHO it is important that each single character should get it's own block, so "ae" uses two blocks with an "a" and an "e" instead of one block which contains both characters.

Regardless, for the words in the bottom right corner I think, they should be written as they are in the word list. They would look strange without Umlaute and ß. Uppercase letters should also be printed as they are in the word list, so that e.g. nouns would start with uppercase characters.

**Comment by qoheniac** [comment]
I personally prefer Ä Ö Ü ẞ over AE OE UE SS, because although not looking super strange words would definitly become harder to recognize. By the way, there is an official way to capitallize ß and Unicode has it. See [Wikipedia](https://en.wikipedia.org/wiki/Capital_%E1%BA%9E) for more information.

**Comment by qoheniac** [comment]
I tried

`aspell -l de_DE dump master | aspell -l de expand | tr ' ' '\n' | grep -Pv "^.+\p{Lu}$" | sort`

and while this looks quite well, I also looked at

`aspell -l de_DE dump master | aspell -l de expand | tr ' ' '\n' | grep -P "^.+\p{Lu}$" | sort`

see what is lost and noticed some very common words like _BÄUME_, _MÄRKTE_ or _GÄNGE_ are thrown away as they are written in all caps for some reason in aspell's output. All these words have in common that they contain an Umlaut, but for example _Läuse_ isn't written in all caps and thus makes it into the word list.

**Comment by Mannshoch** [comment]
This discussion shows several interestings. Maybe there is a need for a set of Options in the settings.

- [ ] Use Crossword rules (ä,ö,ü,ß,é -> ae,oe,ue,ß,e) - Words with special characters may get one character longer
- [ ] Only use base-words without conjugations (so there is a little chance to get them all)

**Comment by d-mal** [comment]
Have you had a look at https://github.com/enz/german-wordlist ?
It's CC0 1.0 Universal licensed, and says it's used by Tanglet. 
It looks good to me. I only noticed some words are in that list twice if they can be spelled with a capital letter and a lowercase letter at the beginning (i.e. summe / Summe). 

Also, IIRC, the hardware boggle game we had used none of the "special" German letters. You had to find AE instead of Ä, and SS instead of ß. I think that's completely OK. 

In case you want to add special letters (as an option?), ÄÖÜ are easy. But "ß" is normally only used as a lowercase letter, since no word starts with ß. If a word with ß in it was written in uppercase, it usually was turned into "SS". This is not ideal: MASSE could mean "Maße" (measurements) or "Masse" (weight). 
Since 2008, there is a uppercase "sharp-s" or "ess-zett" in unicode: ẞ (see https://en.wikipedia.org/wiki/Capital_ẞ ). You could use this letter, or you could instead have a tile with "SS" on it, similar to the "QU". Or you could only add AÖÜ and let ß be two separate S tiles.

**Comment by Mannshoch** [comment]
May as an idea. After I entered a Word, even the word was not in the result list, check it in the dictionary and add a point if it appear there. May giv extra point in that case.

**Comment by d-mal** [comment]
Any news about this? The game is nearly unplayable with the current German dictionary. All the nouns are missing! The list at https://github.com/enz/german-wordlist would be perfectly fine as it is, even without changing anything about special letters.

**Comment by d-mal** [comment]
Hi @pserwylo, [way up in this thread](https://github.com/lexica/lexica/issues/69#issuecomment-386779579)  you wrote

> I've done what you suggested and included words from GNU aspell which start with an upper case letter. This is the list of words which are added to the word list in response:
> 
> https://gist.github.com/pserwylo/27019d0e12483a8ac227d95d802d37ac

I can't see the gist, but I think you did not add the new list to the code? If you don't like the "enz" wordlist, I guess this list will already be much better than what is included now.

**Comment by pserwylo** [comment]
I've gotten the "enz" wordlist, and produced a new dictionary and corresponding set of letter frequencies. However, until #71 is resolved and normalized characters are dealt with correctly, then the German lexicon seem to continuously generate boards with diacritics that are almost exclusively not used.

My question for German speakers:

> *Should we do a release with this new wordlist? Or wait for #71 to be resolved?*

I suspect that #71 will take some time to complete, as I'm about to return from two weeks off work and will find it difficult to find time to work on it. I'd like to release this now, but not sure if I've made things worse.

**Example boards with unused diacritics**

![image](https://user-images.githubusercontent.com/248565/92978876-656b5b00-f4d4-11ea-8e58-5dc181dce009.png) ![image](https://user-images.githubusercontent.com/248565/92978922-8633b080-f4d4-11ea-8250-580ff19273a5.png) ![image](https://user-images.githubusercontent.com/248565/92978951-98adea00-f4d4-11ea-8378-afdff8599bc3.png)

Although as I take screenshots for this comment, I do get some boards which make use of some diacritics:

![image](https://user-images.githubusercontent.com/248565/92978895-7916c180-f4d4-11ea-8dd1-871440581955.png)

**Comment by qoheniac** [comment]
If you implement this, one maybe has to regenerate the board a few times to get one with not too many diacritics and then it will be enjoyable. To me this feels much better than always playing without nouns. Well, it depends a bit on how many trys one usually needs to get a board with less than two diacritics.

**Comment by d-mal** [comment]
I agree with @qoheniac , I believe this would be already better than the current situation even with the diacritics. 

But I think you could just do a dumb search and replace for `àáâåçčéèêēëīíïîłñōóõœšūûú` as these will only show up in a few "loaned" words. Nobody will notice, you could also just throw out those few words ;-) 

You don't have to make a decision about äöüß yet, if you don't feel comfortable about that. Though I would recommend to do a "search and replace" normalization on these as well (always turning them into two letters). It's definitely the standard for word games. Also I think it would be OK to see the words in the result list in the same form too.

**Comment by pserwylo** [comment]
Ah, good pickup @d-mal:

```
grep -P "[àáâåçčéèêēëīíïîłñōóõœšūûú]" dictionary.de_DE.txt| wc -l 
355
```

I'm going to remove those words. For those interested, here is the first handful of them:

```
abbé
abbés
abrégé
abrégés
acheuléen
agrément
agréments
ampère
aperçu
aperçus
apéro
apéros
associé
associés
attaché
attachée
attachéen
attachés
autodafé
autodafés
bahuvrīhi
baoulé
baumégrad
beauté
beautés
bébé
bébés
béchamel
béret
bérets
bergère
bergèren
bésigue
bésigues
bésique
bésiques
bête
bêten
bézigue
bézigues
bézique
béziques
bodhrán
bodhráns
bohème
bohémien
bohémiens
bokmål
bokmåls
botellón
botellóns
bouclé
bouclés
bourrée
bourrées
```

**Comment by pserwylo** [comment]
Thanks to everyone for your help on this. I've tagged v1.3.1 for release which includes the new wordlist. Once F-Droid builds and releases we should be good to go. 

I have left `äöüß` in for now, and will think a little more about how to normalise all languages in #71 for a future release. Rest assured the end goal here is to normalise these dictionaries properly, but I want it to work for all languages, so wont do a dumb search and replace just yet. 

Once released, I'll comment here again, and if anyone can confirm that the version of the dictionary used is good, then we can remove the "(Beta)" from the German language when selecting a lexicon.

**Comment by qoheniac** [comment]
Thank you very much! I really enjoy the game now with this new wordlist and I learned some interesting things from looking up words I didn't know. So far the wordlist works really well and the only strange thing I noticed was that Dublin is included but Rom (Rome) isn't. Nevertheless, I think the "(Beta)" can be removed.

**Comment by qoheniac** [comment]
> ```
> grep -P "[àáâåçčéèêēëīíïîłñōóõœšūûú]" dictionary.de_DE.txt| wc -l 
> 355
> ```

I sometimes still see an Œ in the game. Maybe it's still in there because of some noun in the dictionary starting with that letter so that it is capitalized and wasn't removed? Does ```grep -iP``` give a different result? I cannot check that right now.

**Comment by d-mal** [comment]
Now I've also played quite a few games with the new word list, and I can only second @qoheniac ... It's really much better and nicer! Thanks a lot!

I also have come across a game with an unusual accented letter, so I had a look at https://raw.githubusercontent.com/lexica/lexica/master/assets/dictionaries/dictionary.de_DE.txt

It really has to do with capitalisation: The leftover accented words are:
```
Ångström
Ångströms
Åsar
Œuvre
Œuvres
Šeqel
```
I would be OK with dropping those for now, too. 
For a later version, I guess these would be best changed into "A" "OE" and "S".

**Comment by d-mal** [comment]
I just wanted to play the word "TEE" (tea) but it was not accepted. I checked the dictionary.de_DE.txt and it's not in there. I looked at the list at https://github.com/enz/german-wordlist/blob/master/words and found it. Actually it's in there twice: as "tee" and "Tee". 
Might there be a bug somewhere in the processing of the dictionary that takes out duplicates?

**Comment by d-mal** [comment]
Something unrelated: 
"QU" is usually one block in German Scrabble and Boggle (but not in crosswords). I always thought there are no German words without "u" after "Q", but the wordlist has a few and I checked that at least some of those are valid German words according to "Duden" (the holy grail of German dictionaries). 
So that's a gameplay decision then -- make "Qu" one piece to make it easier and more likely to be useful, but leave out a few other valid words? Or keep "Q" separate, which will most of the time not give any words, but might offer the chance to play a few rare words?

**Comment by Bubu** [comment]
I'm unsure how missing words in the original wordlist should be handled. Reported to https://github.com/enz/german-wordlist or kept track of here?

(I wanted to play https://de.wiktionary.org/wiki/Kelp, but the wordlist only contains all forms of `Kelpwald`, it seems strange that the list contains a composite word but not the separate parts.)

**Comment by d-mal** [comment]
Open an issue at the original place, since it is something missing there. When the original list updates, it can be imported again here.
