### ISSUE TITLE
Normalize accented latin characters (e.g. e vs é vs ê)

### ISSUE THREAD

**Issue by pserwylo** [lexica/lexica#71]
In #27, @ketsa [mentioned the following about French dictionaries](https://github.com/lexica/lexica/issues/27#issuecomment-385264695):

> For the French, do not use accented letters in the grid and do not consider accented letters to be different from standard ones ( `I` = `Ï` = `Î` or `e` = `é` = `ê` etc.) it makes it impossible, just consider them all to be standard, it would be a much better solution.

**Comment by pserwylo** [comment]
Full disclaimer, je ne parle pas français. However, for these Beta languages I have made the game log each word available on each board to Logcat. I sat down after reading your comment and played a few boards. When a board had accented characters, I checked the log for the available letters and it seemed that there was usually a few words available using that character.

I'm concerned that if I normalize these characters as described, that the number of words on each board will become excessive (does anyone want a board with 300 words on it to solve in 5 minutes?). 

With that in mind, I wouldn't mind hearing from a few other French speakers on their opinion. If most want this, then sure, we may as well do it.

**Comment by ketsa** [comment]
> a board with 300 words on it to solve in 5 minutes 

Yes, closer to the English version, why should it be different ?

**Comment by pserwylo** [comment]
I may have mis spoken. The English one typically does somewhere between 50 and 250 words. I'm actually thinking about making the board generator try to have a little less variation in the number of words (e.g. keep generating random boards until it gets between 50 and 100 words - though I don't know what a good number of words is at this point in time, so haven't pursued it).

If I was to do this, then the accented French letters could stay and they would still be able to be used properly. However, I'm really more than happy to delegate to you on what to do with these letters. What I will do though, is to wait for a while to see if other French speakers are able to comment on the situation, to get some sort of agreement. If one or two more French speakers agree, then lets go ahead and think about normalizing these characters.

**Comment by hhassey** [comment]
Please do the same for spanish, accented letters = normal letters

**Comment by nicolasyopmail** [comment]
I'm french (oui, monsieur) and altough you're argument for maintaining accentued letters is good (it adds difficulty to the game and restrain the list of potential responses), I think that the average french player will find more intuitive/easy to play with non-accented letters.

Maybe it could be optionnal ? (a sort of option "level=difficult") 

Another idea : instead of limiting the number of words, why not decrease the "frequency of appearance" (I hope this Google Trad is OK) of the voyels ? or modulate their appearance? (less "e", more "u" or something like that)

**Comment by pserwylo** [comment]
Merci @nicolasyopmail. Thanks for joining the discussion. I've also noticed that CrossWords for Android seems to do this as well, if I'm not mistaken. As such, I think it is something we should implement. Unfortunately, it will require a bit of a change to the guts of Lexica, where the wordlist for each language is stored in a trie, a data structure which makes it quicker to filter through 100k+ words to find the 50-100 which are on a board. Right now, it presumes each letter is distinct.

A quick cheat would be to completely forget about accents, which means that even after selecting the relevant tiles (without accents) and making a word, that word would be displayed without accents as well. 

I'm guessing this is not great though, because the word `déjà` would be built by selecting a `d` tile, an `e` tile, a `j` tile, and an `a` tile. So far so good, it sounds like that is fine for native speakers to manage. However after selecting the word, it would be shown as `deja` instead of `déjà`. Am I correct in thinking that this is just wrong?

If so, we'll need to make some changes to how the data is stored internally. Happy to put the time in, but it wont be able to happen for a while as I have some other commitments right now.

**Comment by edgato** [comment]
I think that conserve the accents is the best option, as it is the right way to write each word.

For example in spanish if you remove an accent the word means something diferent at all, that is how the languages works.

**Comment by Shaac** [comment]
Hello, I’m french, and I must admit I was surprised to see accents in the game. I have never seen a game about letters that uses accents.
Why do game never use accents? I think Scrabble/Boggle & cie don’t use them mainly because they are physical game board and can not have too many letters. But we don’t see them in virtual games neither. Probably because it increases difficulty and adds more very rare letters. In French for instance we do not use the letter W very much. But the letter Ï might be even more rare (just speculating, did not check). So when you add Ï on the board, you will be sure to make almost no words at all. In comparison, the accentuated letter É is more used than W, so it is not always true.

While, as said above, it is true that accents are the correct way to spell a word, and can change the meaning. For instance UN HOMME TUE / UN HOMME TUÉ (a man kill / a man killed: very different meanings), or sometimes I buy in bakeries a PAIN SALE (dirty bread, instead of salted bread, spelled PAIN SALÉ). But this is a game, not a French lesson. People are used to omiting accents in word games.

I played a few games with the current Lexica in French. And while it is interesting and original to play with accents, it is not at all a good default mode. In a 4x4 grid, they are only 20 to 80 words. I mean having Ô and Ï in the same 4x4 grid is simply absurd. It’s like playing in English with X, Z, Q, and J.

So I say, drop the accents in default mode.

**Comment by hhassey** [comment]
I have been playing it in spanish for a while, and actually yes, accented words can be played, maybe they should give you more score points as they are more difficult to use...

**Comment by mhaaz** [comment]
+1 To this request
I speak both Spanish and French natively. While very unusual for a word game to keep the accents in both, in Spanish it is even more ridiculous: an accented letter isn't even a different sound in Spanish. The accent is only to show which syllable is strong, and highly dependent on the word length... This makes it impossible to use the letter tile for words of different length based on the same root, which is a crucial strategy. This destroys much of the fun.

As an example, imagine in English you find "eat" but couldn't use the same tiles at the start of "eatery" or "eating" because the word length required the a to be accented.

**Comment by triNem** [comment]
This issue is very interesting, isn’t it? We should tag it with “fascinating” ;-)

I tried both english and french boards. They both work as they are. Just like @pserwylo said, diacritics (accented letters) tend to increase the variability of the word count. They make the game harder. But they don’t break the game. 

In fact, they can make the game greater : The first time I found “inouï” and then  “inouïe”.  I really enjoyed it. OOOH YES! And since, there is a word count on the screen, we always know if we should (and can) find more words.

But I understand the logic of removing diacritics in word games. Especially if you look for points. Just two or three diacritics usually mean a lower score. 

So I am a little on the fence here. Especially, since this is open source software. I’m not sure we should decide for the players. 

I would go with the **optional** choice. We could have two identical dictionaries: one with diacritics and one without. The “define” option in missed words still works : I tried sale/salé, tue/tué chateau/château inoui/inouï in quickdic. It still finds the words. As a bonus, it requires minimal work.

I also suggest investigating another option : I created post  #110  for a “word search” mode.

We would have two different modes depending on the style of play :
- A points/number of words style mode for hardcore gamers.
- A word search style for beginners, casual gamers and people interested in learning new words. (This might solve issue #95 ).

**Comment by d-mal** [comment]
German native speaker chiming in ;-)
I would love to have an option to turn on "special" letters. But the default should be to normalize to whatever people are used to from crosswords and other word games. The normalization may not be the same for all the languages. French and Spanish seem to drop their diacritics, German turns them into extra letters. It would be interesting to find out what the Dutch do with IJ, or the Danish with Ø or Å in crosswords. 

For German, the crossword rules are to break up ÄÖÜ and ß into two letters: AE,OE,UE,SS. Very few words have been imported from other languages with accents, if such a word shows up in a dictionary, it's safe to remove the accent or even drop that word altogether. 
To make it a bit more complicated, Swiss German has abolished the letter ß in favour of ss. So a crosswords-rule default would work for both Swiss and Germans, but a version that keeps the ß would look a bit odd for the Swiss.

**Comment by rffontenelle** [comment]
In Portuguese (Brazil), same situation as mentioned by @ketsa: accented letters are not used  in the grid neither considered as different from standard ones. Only exception is [ç (c-cedilha)](https://en.wikipedia.org/wiki/%C3%87) which is normally typed C+acute accent.

Quoting [Scrabble_letter_distributions#Portuguese in Wikipedia](https://en.wikipedia.org/wiki/Scrabble_letter_distributions#Portuguese):
> While Ç is a separate tile, other diacritical marks are ignored

**Comment by MCMic** [comment]
I'm french and I like the game as it is, so if you change this please make it optionnal.

**Comment by d-mal** [comment]
Interesting that some people like the accented letters - I guess they do make it more difficult. But I would vote for a normalized playing board as default, since this is the standard of all wordgames. How to get the normalization done is a bigger question.

IMHO ideally the wordlist contains the complete and correct spelling with accents and special characters, and the game does a normalization on the fly to only use "standard" letters on the board. If the player finds a word, it may then be traced back to the original entry in the wordlist to display the fully correct spelling. I've no idea how hard this might be on the performance, but if all this is done on the fly, it could easily be switched off as an option and people could play with accented letters. 
Alternatively, there might be two wordlists, one only containing only the normalized versions, and one with the full versions. How could the game find the full spelling of a normalized word this way? 

Somewhat related: #134

**Comment by pserwylo** [comment]
Tthank you all so much for your contributions to this. I am determined to get this going because it seems like something that is important to getting the experience right.

There are two approaches, one is much simpler than the other, but depends on the answer to the following question:

> *How important is it that the non-accented characters (e.g. "deja") shown on the board display as the correct word (e.g. "déjà") elsewhere in the game, such as end of game word lists, recent word list during game play, navigating to dictionary definition, etc.*

**If the answer is "doesn't matter, just show the word deja everywhere":**

The simple solution will be to produce a new dictionary without accented characters. We can either replace the existing dictionary completely, so that all, e.g. French, games will never have accented characters anywhere. Alternatively, we can have two dictionaries: "French (with diacritics)" and "French (without diacritics)". This would satisfy the desire of some people to play with the more challenging boards.

**If the answer is "it is important, that after selecting a word without diacritics, the correct word is then used everywhere else":**

This is still possible, but will require more changes to the internal representation of words right now, which assumes one canonical representation of a word. Although it requires pulling the internal data structures apart and putting them back together, at least there is now pretty good test coverage of this part of the code.

Both are possible, but am keen to get a little feedback from non-English speakers of various languages prior to commencing the more difficult reworking - as this will mean less time to work on other features and bug fixes.

**Comment by matttbe** [comment]
First, thank you for developing and maintaining this good game!

Hi @pserwylo 

> There are two approaches, one is much simpler than the other, but depends on the answer to the following question:

If I may, I would suggest to focus on a simpler approach first: having an option to "normalise" the words when parsing the dictionary file. All words from the game will be without accents and that's the main use of the app. Note that at least in French, when you write words in capital letters, it is normal not to put accent on them.

Note that after "normalisation", it is possible to have duplicated words: sûr vs sur, dû vs du, cote vs côte vs coté vs côté vs Côte, etc. but I guess this is already managed when parsing words.

If needed, displaying words with accents could be added later, especially if this needs a lot more work only for a few words.
I didn't look at the implementation but maybe when parsing the dictionary file, it is possible to add both the normalised word and the original one in the class used to represent the word? We could then have a `getOriginalWord()` in some cases.
To save a bit of memory and if a hashmap (or similar) is used, the normalised word could be used for the key. In the value part, only the original word could be present instead of the two.
Again, I didn't look at the implementation!

I am far from being a "heavy player" but I am not often using the "dictionary definition" feature.
Please also note that in QuickDic app, if I type `deja`, `déjà` word is found. So maybe if all words are managed without accents and display in capital letters, that's not a problem at all :)

**Comment by d-mal** [comment]
IMHO it would be fine for German to see the normalized word everywhere. That feels okay for a word game, since the user also will be entering the words this way. I tried the "definition" function, too, and it seems as if this is also no problem: Duckduckgo will find links to the definition of a word even if it is "MAESSIG" instead of "mäßig".

**Comment by pserwylo** [comment]
@matttbe: Thanks for the insight. The internal data structure is a trie. This *used* to be really compact and also really fast to lookup at runtime (from way back in [2009 when Android phones were really just on the market!](https://github.com/lexica/lexica/commit/d8c329c97a844548aea08447f15bdb674b1eee76)). Now they actually bigger, because I had to switch from an ASCII numeric representation to a unicode string representation in order to support multiple languages (as I write this, perhaps I should have stuck with integers!). This means the size of the trie is bigger than the flat dictionary file, but it is still extremely fast to query at runtime. As I'm writing this though, I'm starting to think that for the price of a brief loading screen, dealing with flat files may be much easier. I'll  ponder it a it further.

@d-mal: Perhaps a silly question, but in the example above, could you please explain how the `ä` character becomes `AE`? I ask because my thought for normalizing is to ask Java to decompose the unicode character into `a` + `umlaut`, then only take the first character. However it sounds like I'm mistaken in this approach.

**Comment by d-mal** [comment]
Not a silly question, it's just how it is done in German. If you don't have the ability to write a letter with umlaut, Germans will always change these into two separate letters `ä`->`ae`, `ö`->`oe`, `ü`->`ue` and the same for the capitals `Ä`->`AE`, `Ö`->`OE`, `Ü`->`UE`. It seems that there was a historic development from `AE` via `Aͤ` (A with a little e on top) to `Ä`. 

The third "special letter" in German is the "sharp s" or "es-zett". The replacement should be `ß`->`ss`. 
The history of this ligature is [well described at Wikipedia](https://en.wikipedia.org/wiki/ß). Interestingly, until very recently, there was no capital form of ´ß´, since no word starts with this letter. Unicode has accepted a capital sharp s: `ẞ` in 2008, see also [Wikipedia on the capital ẞ.](https://en.wikipedia.org/wiki/Capital_ẞ)  But this is not (yet?) very common, and in crosswords you'll only find `SS`.

If a loan word from another language shows up in word games, diacritics are always dropped: `café`->`cafe`, `señor`->`senor`.

**Comment by d-mal** [comment]
Other languages and countries also seem to have their own "crossword rules", see [https://en.wikipedia.org/wiki/Crossword#Orthography](https://en.wikipedia.org/wiki/Crossword#Orthography)

**Comment by matttbe** [comment]
@pserwylo : thank you for your reply!

> The internal data structure is a trie. This used to be really compact and also really fast to lookup at runtime (from way back in 2009 when Android phones were really just on the market!).

I didn't know the first version was that old :-)
The trie data structure totally makes sense, I forgot about it!

> As I'm writing this though, I'm starting to think that for the price of a brief loading screen, dealing with flat files may be much easier.

Do you mean that the trie is built when packaging the app not to have to parse the flat dictionary file at all on Android?

**Comment by lgommans** [comment]
@d-mal Did you mean the second Orthography section? That seems to include a list of suggestions for various languages. https://en.wikipedia.org/wiki/Crossword#Orthography_2

To comment on the Dutch entry: it says *ij* is considered one letter, but I find that odd or perhaps just outdated. We use the letters separately as well as together (*jong imitatieijs* (young imitation-ice)) so of the three words you'd be able to make only *ijs* if *ij* is one square. To me they're just separate, a bit as if you'd put *ea* in one square to make words like *easy* or *ear* but not *apple* or *rest*. But don't let one person's opinion decide that :).  
As for diacritics, just drop them in all cases. It would be cool if the word shows up correctly after swiping it (swipe *cafe* -> show *café*), but definitely not necessary. I.e. [this](https://github.com/lexica/lexica/issues/71#issuecomment-684115616):

> The simple solution will be to produce a new dictionary without accented characters.

would be fine for Dutch.

**Comment by d-mal** [comment]
> Did you mean the second Orthography section?

Oh, yes of course... thanks for fixing the link.

**Comment by pserwylo** [comment]
Okay, here we go: [v2.1.0 has been tagged](https://github.com/lexica/lexica/releases/tag/v2.1.0) ready to be built by F-Droid. It includes two dictionaries for French and two for German (one with and one without diacritics). Turns out it was much simpler to do this than to try and write language specific rules about how to treat specific characters.

It doesn't include Weblate translations yet, but as they role in, I'll bump minor releases to include them (as they will have translations for these new dictionary descriptions) - just keen to get feedback on the actual dictionaries. Thanks again for all your input, this really wouldn't be such an international game without input from those in the community helping to ensure their language is supported.

I'll close this issue now, because on a case by case basis we will now add separate dictionaries per language, tracked in separate issues (e.g. I'll be off to sort out Italian as per #121 next).
