### ISSUE TITLE
Polish (PL)

### ISSUE THREAD

**Issue by alekksander** [lexica/lexica#89]
i could translate to polish and provide pl dict.

**Comment by pserwylo** [comment]
Dziękuję! That would be great! For translations, we use Weblate ([see here](https://github.com/lexica/lexica#translating)). With regards to the dictionary, I'd appreciate a high quality Polish dictionary that is freely licensed. For comparison, here is a dump of the `aspell-pl` dictionary: https://gist.github.com/pserwylo/8f43b0f11b4d811dc049d2c6c38fe46b.

**Comment by bzaborow** [comment]
Hi!
it seems there is no progress here, so maybe I can help? There is a Polish dictionary available on open license, developped by community: [sjp.pl](sjp.pl). The zipped list of words can be downloaded here: [https://sjp.pl/slownik/growy/](https://sjp.pl/slownik/growy/). It is a subset of the whole dictionary, dedicated for scrable-like games, so it should fit the Lexica needs perfectly (rules for deciding if a word is suitable for games are [here](https://sjp.pl/slownik/dp.phtml), in Polish only unfortunately...). The dictionary is pretty high quality, it is based on various printed dictionaries. As far as I remember it was used in some opensource linguistic tools like morphological analyser Polimorf (developed by Polish Academy of Sciences).
By the way, sjp.pl could (and should) be used for defining words - the search engine is on sjp home page. I can later figure out if there are some tricks/escapes needed for passing the argument, but generally the search results are under `https://sjp.pl/<searched word>`, e.g. [https://sjp.pl/tester](https://sjp.pl/tester)

**Comment by alekksander** [comment]
@pserwylo can You add the file provided by @bzaborow ?

**Comment by pserwylo** [comment]
Thanks for the prompt @alekksander, I've gone ahead and produced a build with this Polish dictionary. Thank you so much for your detailed comment @bzaborow, it made it very easy to add this - thanks for your patience :)

In addition, I've also changed the "Definition Provider" option from "DuckDuckGo" to "Online". When selected, every language except Polish will use DuckDuckGo (which may or may not work well, depending on your devices locale). The Polish version will use https://sjp.pl when defining words instead. In the future, other languages can opt to use their own, more appropriate, online dictionaries.

I'd love if I could get some feedback from native Polish speakers as to whether it is playable. Here is a debug build you can try. You'll need to remove the existing version of lexica, rename this file to a `.apk` instead of `.zip` (GitHub doesn't allow attaching APK files to comments), and then remember to uninstall this version in order to go back to the official build.

[lexica-polish-debug-build.zip](https://github.com/lexica/lexica/files/4465628/lexica-polish-debug-build.zip)

If I can get an okay from a native speaker, then I'll remove the "Beta" option from Polish before releasing, because this is already a curated dictionary (not the contents of a spell checkers dictionary like other languages are currently using).

**Comment by bzaborow** [comment]
What a nice news today! Thank you @pserwylo! I installed the debug build you provided, it is definitely playable and works great. It feels slightly more difficult than the English, perhaps just because Polish has longer words at the average.
So, as a native speaker, I vote for removing the "Beta" mark. Yes, I might be unobjective here;)

**Comment by alekksander** [comment]
i second @bzaborow opinion. there are some doubtful words inside the dict., but it doesn't regard application itself ofc.

thank You both

**Comment by pserwylo** [comment]
Thanks all. Beta label has been removed and it is merged into `master` now.

I'll wait a week or so prior to releasing, which will give some time for the wonderful community of translators on Weblate to add their translation for "Polish", but also the new "Online" dictionary option that replaces "DuckDuckGo".

Once a release is pushed, F-Droid will build it when it gets time. Once released, if you find any issues with the Polish dictionary, please open a new issue and we'll do our best to address it.

**Comment by pserwylo** [comment]
This is now available on [F-Droid](https://f-droid.org/packages/com.serwylo.lexica/), [GitHub](https://github.com/lexica/lexica/releases/tag/v0.12.1), and I'll upload to the Google Play Store tomorrow.
