### ISSUE TITLE
Settings change isn't handled properly.

### ISSUE THREAD

**Issue by Hypoon** [lexica/lexica#96]
Set the board size to 4x4, then start a new game. Go back to the settings, and change the board size to 6x6. Now resume the game. You'll still be playing the 4x4 board, but that's not necessarily a bug. When you finish the game, your high score gets saved to the 6x6 slot (the current setting), even though you just finished a 4x4 game (the previous setting). That's definitely a bug. I'm running version 0.11.4.

**Comment by pserwylo** [comment]
Oh wow, great pick up. Thanks for the report.

**Comment by RustanHakansson** [comment]
This bug is still sort of active. When I do as described, switching from an in-progress 4x4 game to 6x6, I get a new game. When I switch from an in-progress 6x6 to 5x5, I continue the game as 6x6. I suggest that if there is an ongoing game, and the user choose the setting to change board size, add a small text to that dialog that says "The current game will be aborted if you change board size." and do exactly that if the user changes the board size.

**Comment by pserwylo** [comment]
Closing as I suspect this has been addressed in v2.0.0 where many settings (including board size) was replaced with game modes, and the way high scores are saved has been overhauled.

As always, please feel free to reopen if this is still an issue, or create a new issue if there is any other issues.
