### ISSUE TITLE
Design draft

### ISSUE THREAD

**Issue by elbotho** [lexica/lexica#97]
🍉  I made a quick design draft.

I tried to leave most of the logic as it is. There are two simplifications to make it look a bit clearer.
(no score display for individual words, no space for the word length breakdown so far, both could be added though)

Font: Draft uses [Rubik](https://fonts.google.com/specimen/Rubik) that comes with lovely rounded letters and quite a good language support itself but could be replaced with [Noto](http://www.google.com/get/noto/) for unsupported languages.

There's a light and a dark variant. If you play at night the later one might be easier on the eyes.

![lexica_redesign_draft](https://user-images.githubusercontent.com/1258870/43369029-eff019fe-9366-11e8-9f1d-14ee14081a4f.png)

What do you think? Somebody interested in implementing it?

**Comment by elbotho** [comment]
Thank you @pserwylo this is the kind of feedback I need to take on the rest of the design :)
Also I agree with your feedback.

---

Todos:
- [ ] add more contrast to the info section 🌘 :
- [ ] home screen design 🏠 
- [ ] end game screen design 🎉 
- [ ] (matching, international logo #65) 🌐 
- [ ] interactive states, highlight colors, … 🔆 
- [ ] provide assets, values etc. / at least svg file 📁 
- [ ] word history right to left for r2l languages ⬅️

**Comment by pserwylo** [comment]
Sounds great. While I cant implement this over the coming months, I'd be more than happy to provide feedback on this (or any associated threads). Who knows, perhaps I'll find some time here or there to start getting little bits of the design in (rather than waiting to do one big overhaul at the end)! Thanks again.

**Comment by elbotho** [comment]
Just a quick update, other screens basically done. Details and cleanup still WIP.
Splash not 100% but at least it's animated :)

![image](https://user-images.githubusercontent.com/1258870/44024809-aaf9b128-9eee-11e8-855f-1c4393ba0d57.png)
![image](https://user-images.githubusercontent.com/1258870/44024942-f6ac459a-9eee-11e8-9a5a-4bb3a1a41910.png)

**Comment by pserwylo** [comment]
Some feedback on your updated mockups. Hope you don't mind me being direct with both the things I like and the things that irk me a little. Please tell me if I'm being rude or unreasonable. Of course, I also realise these are WIP, but thought the earlier we get onto feedback, the better.

Things I like:

 * The general layout of the final score screen.
   * I'd probably swap the "Time" and "Words" panels in the bottom of the game screen, so that they line up with the final screen (words on the left, score on the right).
   * I especially like the separation between the game board and the word list in your final game screen, particularly in the yellow theme.
 * The new game button on the home screen.
 * The high score on the home screen. Perhaps we could also incoporate the currently selected game type? Maybe with icons for each different variation:
   * Game board size (4x4, 5x5, 6x6)
   * Time limit
   * Word breakdowns enabled or not
   * etc?
   * It might appear obtuse to new players who don't know what they mean, but frequent players would benefit, and perhaps even touching them would take you to a game-mode selection screen where you can choose which settings to enable. 

Things I'm not as big a fan of:

 * In the dark theme, orange buttons on the final two screens mean the button is highlighted, however on the home screen it means "This is the button you probably want to press".
  * I like the orange new game button (even more than the new game button in the light theme), but I also appreciate the importance of showing the selected tab on the last two screens.

 * The bottom button bar on the home page and the final screen concerns me a little though, because it looks like it should behave the same as the score/time/words section in the game, but of course that section doesn't have any button-like behaviour.
   * In addition, this may be just my old-android-developer-hat, but it feels a lot like the [original tab bar in early versions of Android](https://f-droid.org/assets/posts/2017-04-04-new-ux/0.11.png), which in itself is not a bad thing, but because of the baggage of old android themes, makes the app feel to me like an older android app to me, rather than the more modern version which your UI is pushing it towards. 
 * While I appreciate you taking the contrast into consideration, the "Time/Words/Score" section in the light theme doesn't seem as beautiful as before. Not sure how to fix this though, because in general low contrast themes seem to be perceived by many as more sleek and elegant, but of course less functional.
Things I'm indifferent about:

 * The main screen logo. I think it looks okay, someone looking over my shoulder was a bit confused by it.

**Comment by pserwylo** [comment]
Regarding my thoughts about the low contrast version looking better... I wonder if it is not as important as I think, because we are going to offer multiple themes and the user is free to switch to the dark theme, which has much stronger contrast everywhere?

**Comment by airon90** [comment]
Any update?

**Comment by pserwylo** [comment]
Sure! So I've been super busy with teaching this semester, but earlier I managed to get a few additions, specifically around the addition of selected words:

![highlighted-words](https://user-images.githubusercontent.com/248565/46655168-87784680-cbf6-11e8-850c-72c435d46ba9.png)

You can see the progress in my [new-ui](https://github.com/pserwylo/lexica/tree/new-ui) branch - no promises of stability, and still has some work to go!!!

My work schedule will keep me busy for the next few weeks. Then, I should have at least a little time to hack on this over the end of Oct, start of Nov.

**Comment by elbotho** [comment]
Same here. But I will get back to your feedback @pserwylo.

**Comment by Coruna** [comment]
Whats the status of the new design? I'd love to see it in the app :slightly_smiling_face:

**Comment by KeronCyst** [comment]
That dark mode looks glorious. I came here specifically to request that.

**Comment by elbotho** [comment]
@pserwylo what do you think should we give this another go? :)

**Comment by pserwylo** [comment]
Absolutely! I've been a bit absent on free software projects in general lately due to work and (wonderful) family changes. But I'm keen to pursue this further. I previously got a a point where I'm very happy with the main game screen, have made a start on the home screen, and only just began working on the post-game screen(s) prior to stopping work some time ago. I'll make sure my latest changes are in git, and then can resume work at a slow pace again to see if we can crawl to completion. 

Would you like to help with the Android dev? Okay if not, I still value your design input.

**Comment by elbotho** [comment]
@pserwylo sounds great! 
I decided against also learning native app dev. Stretching myself thin with UX,UI and webdev already :) 

btw: I started with an reactjs version of the game just too see how hard it would be. got to a pretty and nearly playable prototype if you are interested in a version that also runs on desktops :)

But now let's get to your feedback finally…

> I'd probably swap the "Time" and "Words" panels in the bottom of the game screen

Sure, good idea!


> Perhaps we could also incoporate the currently selected game type? Maybe with icons […]

Maybe as a bonus if the rest of the UI is working?


> In the dark theme, orange buttons on the final two screens mean the button is highlighted, however on the home screen it means "This is the button you probably want to press".

You are right of course. I'll add another shade or color. I obviously tried to avoid that, but I try not to be stubborn :)

> The bottom button bar on the home page and the final screen concerns me a little though, because it looks like it should behave the same as the score/time/words section in the game, but of course that section doesn't have any button-like behaviour.

Hmm, personally I think style wise the distinction would be fine (on the game footer: no seperator, no icons, different background color). The biggest problem is position and the three sections I guess.
But I like it at the bottom, so I'd suggest leaving it like it is and testing if ppl get confused.

> In addition, this may be just my old-android-developer-hat, but it feels a lot like the original tab bar in early versions of Android

Jup, I see what you mean. Most modern tab-bars just don't use text which is not great for usability imo, especially if it's not an app you use everyday. 
Do you have any ideas/examples? What would make it more "modern"?

> While I appreciate you taking the contrast into consideration, the "Time/Words/Score" section in the light theme doesn't seem as beautiful as before. Not sure how to fix this though, because in general low contrast themes seem to be perceived by many as more sleek and elegant, but of course less functional.
> ... Regarding my thoughts about the low contrast version looking better... I wonder if it is not as important as I think, because we are going to offer multiple themes and the user is free to switch to the dark theme, which has much stronger contrast everywhere?

Okay, a compromise: On the bright theme use the background colors from my second draft but only use white font in the footer (not the black). A bit more contrast with less …elegancy-loss.
And if there is some kind of theming set up, we might as well create a nice high contrast b/w theme for example.

> Things I'm indifferent about: The main screen logo. I think it looks okay, someone looking over my shoulder was a bit confused by it.

To be honest I feel the same way. What I liked most about it is the animation:

![image](https://filebin.net/pelthsr5bi89dgpz/lexica_logo_animated.svg?t=vr8rf46u)


Conclusion:
It seems to me that most things can be addressed by tweaking the color values in the themes.
Do you see any blockers for your work atm.?

**Comment by pserwylo** [comment]
Alrighty, I've gotten some more time to work on this, and now have something almost complete:

[com.serwylo.lexica.NEW_UI.LIGHT_THEME.zip](https://github.com/lexica/lexica/files/4618652/com.serwylo.lexica.NEW_UI.LIGHT_THEME.zip)

**If testing, please report any bugs / feedback in this issue thread**

(You'll have to download, change the extension from .zip to .apk, uninstall the official build of Lexica, install this, then remember to uninstall and go back to the official build afterwards - perhaps in the future I will setup some sort of nightly build so this hackery is not required :)



The only outstanding tasks for the light theme are:
 * [ ] RTL support for the list of words being selected during the game.
 * [ ] Extract the "Hint Mode" colours into the theme - currently hard coded in Java.
 * [ ] Highlight the currently displayed word in end of game scoring.
 * [ ] Extract the yellow highlight colour into a theme colour and use that for currently selected words.
 * [ ] The icon should no longer be blue.

Some deviations from the mockups, based on random play testing during development of the new theme, happy for feedback:
 * Sometimes using light fonts instead of dark where it seemed to work better.
 * Icon choices (e.g. during the end game score view).
 * Add a view/define button for each word in the score activity. The view button is probably not neccesary and could instead be done by touching the entire word (which would work well) but I was keen to get a playable version out. The define button is more of an implementation constraint. Unfortunately we can't "show definitions" for all words at once. In addition, if we were to stick with the method of 1) selecting a word, 2) clicking "show definition", then it would only work for the "missed words" UI, not the "found words" UI. We still need to be able to define words on the "Found Words" panel.
 * The home screen background has remained ostensibly as-is. I'm still quite fond of the existing screen :)

I think it will be best to get this stable and released, and *then* implement the dark theme. Otherwise I'll procrastinate on it forever. I don't anticipate it being difficult to change to dark. Once all of the refactoring is complete, this is the final theme file which needs to be modified:

```styles.xml
    <style name="AppTheme.Base" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>

        <item name="scoreHeadingTextSize">@dimen/scoreHeadingTextSize</item>
        <item name="scoreTextSize">@dimen/scoreTextSize</item>
        <item name="scorePadding">@dimen/scorePadding</item>
        <item name="scorePaddingHalf">@dimen/scorePaddingHalf</item>

        <item name="tileForegroundColour">@color/tileForegroundColour</item>
        <item name="tileBackgroundColour">@color/tileBackgroundColour</item>
        <item name="tileBorderColour">@color/tileBorderColour</item>
        <item name="currentWordColour">@color/currentWordColour</item>
        <item name="previouslySelectedWordColour">@color/previouslySelectedWordColour</item>
        <item name="selectedWordColour">@color/selectedWordColour</item>
        <item name="notAWordColour">@color/notAWordColour</item>
        <item name="scoreBackgroundColour">@color/scoreBackgroundColour</item>
        <item name="timerBackgroundColour">@color/timerBackgroundColour</item>
        <item name="timerStartForegroundColour">@color/timerStartForegroundColour</item>
        <item name="timerMidForegroundColour">@color/timerMidForegroundColour</item>
        <item name="timerEndForegroundColour">@color/timerEndForegroundColour</item>
        <item name="scoreHeadingTextColour">@color/selectedWordColour</item>
        <item name="scoreTextColour">@color/selectedWordColour</item>

        <item name="currentWordSize">@dimen/currentWordSize</item>

        <item name="homeScreenLetterPadding">@dimen/homeScreenLetterPadding</item>
        <item name="padding">@dimen/padding</item>
        <item name="timerHeight">@dimen/timerHeight</item>
        <item name="timerBorderWidth">@dimen/timerBorderWidth</item>
        <item name="tileBorderWidth">@dimen/tileBorderWidth</item>
        <item name="textSizeMinimum">@dimen/textSizeMinimum</item>
        <item name="textSizeSmall">@dimen/textSizeSmall</item>
        <item name="textSizeNormal">@dimen/textSizeNormal</item>
        <item name="textSizeLarge">@dimen/textSizeLarge</item>

        <item name="homeScreenButtonPadding">@dimen/homeScreenButtonPadding</item>
        <item name="homeScreenHighScoreLabelColour">@color/homeScreenHighScoreLabelColour</item>
        <item name="homeScreenMainButtonBackground">@color/homeScreenMainButtonBackground</item>
        <item name="homeScreenMainButtonBackground_focused">@color/homeScreenMainButtonBackground_focused</item>
        <item name="homeScreenSecondaryButtonBackground">@color/homeScreenSecondaryButtonBackground</item>
        <item name="homeScreenSecondaryButtonBackground_focused">@color/homeScreenSecondaryButtonBackground_focused</item>
        <item name="homeScreenSecondaryButtonBackground_disabled">@color/homeScreenSecondaryButtonBackground_disabled</item>
        <item name="homeScreenSecondaryButtonTextColour">@color/homeScreenSecondaryButtonTextColour</item>
        <item name="homeScreenSecondaryButtonTextColour_disabled">@color/homeScreenSecondaryButtonTextColour_disabled</item>
    </style>
```

**Comment by pserwylo** [comment]
![Lexica light view](https://user-images.githubusercontent.com/248565/81751434-bd785d80-94f2-11ea-82b3-7ffcabd1bb39.png)

**Comment by elbotho** [comment]
@pserwylo thank you very much for implementing and improving.
just installed the app after a long time and I think it looks great!

**Comment by pserwylo** [comment]
Glad you like it @elbotho, thanks for the designs. After a lot of usage, I still think it is very nice and am extremely happy.
